// Poker Face (Lionade Party) — curated fact cards.
//
// Moved out of the competitive arena 2026-05-28 (see project_lionade_party.md +
// project_competitive_modes.md). Poker Face is now an N-player party game: one
// presenter per round draws a card in secret, then chooses to either present the
// TRUE fact as written, or invent a LIE (an edited claim) and present that. The
// rest of the room calls BELIEVE or DOUBT. The LIE is always player-authored —
// we never generate it. NO Fang wager, NO ELO: pure points / bragging rights.
//
// Because the game is "best in person," the presenter's FACE is the tell — there
// is no confidence-wager mechanic (that was a remote crutch in the old duel).
//
// These 51 cards were harvested verbatim from the retired
// lib/competitive/pokerface-cards.ts. Content is well-established, verifiable
// trivia, kept family-safe.

export interface PokerFaceCard {
  /** The subject word shown on the card (NOT secret — the room sees it). */
  word: string;
  /** A verifiably TRUE fact about the word. SECRET until reveal: the presenter
   *  may show this verbatim (truth) or invent a false claim instead (lie). */
  fact: string;
}

export const POKERFACE_CARDS: PokerFaceCard[] = [
  { word: "Octopus", fact: "An octopus has three hearts." },
  { word: "Honey", fact: "Honey never spoils and can last thousands of years." },
  { word: "Bananas", fact: "Bananas are botanically classified as berries." },
  { word: "Eiffel Tower", fact: "The Eiffel Tower can grow more than 15 centimeters taller in summer heat." },
  { word: "Sharks", fact: "Sharks existed before trees did." },
  { word: "Venus", fact: "A day on Venus is longer than its year." },
  { word: "Wombat", fact: "Wombats produce cube-shaped droppings." },
  { word: "Hawaii", fact: "Hawaii is the only U.S. state that grows coffee commercially." },
  { word: "Saturn", fact: "Saturn is the least dense planet and would float in a large enough body of water." },
  { word: "Mosquitoes", fact: "Mosquitoes are considered the deadliest animal to humans by transmitted disease." },
  { word: "Eyes", fact: "The human eye can distinguish roughly ten million different colors." },
  { word: "Cleopatra", fact: "Cleopatra lived closer in time to the Moon landing than to the building of the Great Pyramid." },
  { word: "Sloths", fact: "Sloths can hold their breath longer than dolphins can." },
  { word: "Lightning", fact: "A single lightning bolt can be hotter than the surface of the Sun." },
  { word: "Penguins", fact: "Emperor penguins can dive deeper than 500 meters." },
  { word: "Stomach", fact: "The lining of the human stomach replaces itself every few days." },
  { word: "Mount Everest", fact: "Mount Everest is not the tallest mountain measured from base to peak; that is Mauna Kea." },
  { word: "Koalas", fact: "Koalas have fingerprints almost indistinguishable from human ones." },
  { word: "Greenland", fact: "Greenland is mostly covered by ice despite its name." },
  { word: "Spiders", fact: "Spider silk is, by weight, stronger than steel." },
  { word: "Pluto", fact: "Pluto has never completed a full orbit since its discovery in 1930." },
  { word: "Bees", fact: "Honeybees can recognize individual human faces." },
  { word: "Tongue", fact: "The idea that the tongue has separate taste zones is a long-debunked myth." },
  { word: "Antarctica", fact: "Antarctica is technically the world's largest desert." },
  { word: "Giraffes", fact: "A giraffe has the same number of neck vertebrae as a human: seven." },
  { word: "Diamonds", fact: "Diamonds are not the rarest gemstone; many others are far scarcer." },
  { word: "Jupiter", fact: "Jupiter has the shortest day of any planet in the solar system." },
  { word: "Hummingbirds", fact: "Hummingbirds are the only birds that can fly backwards." },
  { word: "Salt", fact: "There was a time when salt was so valuable it was used to pay Roman soldiers." },
  { word: "Brain", fact: "The human brain uses roughly 20 percent of the body's total energy." },
  { word: "Kangaroos", fact: "Kangaroos cannot move backwards easily because of their tail and leg structure." },
  { word: "The Moon", fact: "The Moon is slowly drifting away from Earth, a few centimeters each year." },
  { word: "Cashews", fact: "Cashews grow attached to the bottom of a fruit called the cashew apple." },
  { word: "Flamingos", fact: "Flamingos are born grey and turn pink from the food they eat." },
  { word: "Iceland", fact: "Iceland has no mosquitoes living naturally on the island." },
  { word: "Snails", fact: "Some snails can sleep for up to three years at a time." },
  { word: "The Pacific", fact: "The Pacific Ocean is wider than the Moon's diameter." },
  { word: "Carrots", fact: "Carrots were originally purple before orange varieties were cultivated." },
  { word: "Cows", fact: "Cows have best friends and can become stressed when separated from them." },
  { word: "Lobsters", fact: "Lobsters were once considered a poor person's food in colonial America." },
  { word: "Niagara Falls", fact: "Niagara Falls has been deliberately shut off by engineers in the past." },
  { word: "Ostriches", fact: "An ostrich's eye is larger than its brain." },
  { word: "Vatican City", fact: "Vatican City is the smallest country in the world by both area and population." },
  { word: "Tomatoes", fact: "Tomatoes are botanically a fruit but were legally ruled a vegetable in the U.S." },
  { word: "Elephants", fact: "Elephants are one of the few animals that appear to recognize themselves in a mirror." },
  { word: "Mercury", fact: "Mercury is the closest planet to the Sun but not the hottest; Venus is hotter." },
  { word: "Bamboo", fact: "Some species of bamboo can grow nearly a meter in a single day." },
  { word: "Polar Bears", fact: "Polar bears have black skin underneath their translucent fur." },
  { word: "The Sahara", fact: "The Sahara desert occasionally gets snowfall in some regions." },
  { word: "Owls", fact: "Owls cannot move their eyeballs, so they rotate their heads instead." },
  { word: "Coconuts", fact: "Coconuts are not nuts; they are classified as a type of fruit called a drupe." },
  { word: "The Great Wall", fact: "The Great Wall of China is not visible to the naked eye from space." },
  { word: "Otters", fact: "Sea otters hold hands while they sleep so they don't drift apart." },
  { word: "Scotland", fact: "Scotland's official national animal is the unicorn." },
  { word: "Bubble Wrap", fact: "Bubble wrap was originally invented to be textured wallpaper." },
  { word: "Sea Cucumbers", fact: "Some sea cucumbers breathe through their backside." },
  { word: "Ketchup", fact: "Ketchup was sold in the 1830s as a medicine for an upset stomach." },
  { word: "Avocados", fact: "Avocados are botanically a berry, while strawberries are not." },
  { word: "Pineapples", fact: "A single pineapple takes about two years to grow." },
  { word: "Roman Concrete", fact: "Ancient Roman concrete grows stronger over time when exposed to seawater." },
  { word: "Mantis Shrimp", fact: "A mantis shrimp can throw a punch that accelerates as fast as a .22 caliber bullet." },
  { word: "Nintendo", fact: "Nintendo was founded in 1889 and originally made handmade playing cards." },
  { word: "Oxford University", fact: "Oxford University is older than the Aztec Empire, with teaching there dating back to 1096." },
  { word: "Sea Otters", fact: "Sea otters have the densest fur of any animal, with up to a million hairs per square inch." },
  { word: "Butterflies", fact: "Butterflies taste with sensors on their feet." },
  { word: "Neptune", fact: "A single year on Neptune lasts about 165 Earth years." },
  { word: "Wasabi", fact: "Most wasabi served outside Japan is actually dyed horseradish, not real wasabi." },
  { word: "Apples", fact: "Apples float in water because roughly a quarter of their volume is air." },
  { word: "Turtles", fact: "Some turtles can breathe through their rear ends while hibernating underwater." },
  { word: "Peanuts", fact: "Peanuts are not true nuts; they are legumes that grow underground." },
  { word: "The Nile", fact: "The Nile flows from south to north, emptying into the Mediterranean Sea." },
  { word: "Chameleons", fact: "A chameleon's tongue can be longer than its entire body." },
  { word: "Glass", fact: "Glass is made by melting sand at very high temperatures." },
  { word: "Starfish", fact: "Starfish have no brain and no blood, using seawater to move nutrients around." },
  { word: "Sunflowers", fact: "Young sunflowers track the Sun across the sky, a behavior called heliotropism." },
  { word: "Crocodiles", fact: "Crocodiles cannot stick out their tongues because it is attached to the roof of their mouth." },
  { word: "Uranus", fact: "Uranus rotates on its side, effectively rolling along its orbit like a ball." },
  { word: "Vanilla", fact: "Natural vanilla comes from the seed pod of a type of orchid." },
  { word: "Rats", fact: "Rats laugh when tickled, making ultrasonic sounds too high for humans to hear." },
  { word: "The Dead Sea", fact: "The Dead Sea is so salty that people float on its surface without effort." },
  { word: "Ants", fact: "The combined weight of all ants on Earth is estimated to rival that of all wild birds and mammals." },
  { word: "Peppers", fact: "The heat of chili peppers is measured on a scale called Scoville units." },
  { word: "Dolphins", fact: "Dolphins sleep with only half their brain at a time so they can keep surfacing to breathe." },
  { word: "Redwoods", fact: "Coast redwoods are the tallest living trees on Earth, growing over 100 meters tall." },
  { word: "Frogs", fact: "Some frogs can survive being frozen solid over winter and thaw back to life in spring." },
  { word: "The Statue of Liberty", fact: "The Statue of Liberty's copper surface turned green over time due to oxidation." },
  { word: "Camels", fact: "A camel's hump stores fat, not water." },
  { word: "Watermelon", fact: "Watermelon is more than 90 percent water by weight." },
  { word: "Squirrels", fact: "Squirrels plant thousands of trees by forgetting where they buried their nuts." },
  { word: "Australia", fact: "Australia is wider from east to west than the Moon is across." },
  { word: "Goldfish", fact: "Goldfish can remember things for months, not just a few seconds." },
  { word: "Volcanoes", fact: "There are active volcanoes on other bodies in the solar system, including Jupiter's moon Io." },
  { word: "Coffee", fact: "Coffee was originally eaten as a food before it was brewed as a drink." },
  { word: "The Amazon", fact: "The Amazon rainforest produces a large share of the world's oxygen but consumes much of it too." },
  { word: "Pearls", fact: "Pearls dissolve in vinegar because they are made mostly of calcium carbonate." },
  { word: "Woodpeckers", fact: "A woodpecker's tongue can wrap around the back of its skull to cushion its brain." },
  { word: "Lego", fact: "Lego produces more tiny tires each year than any actual tire manufacturer makes real tires." },
  { word: "Axolotl", fact: "Axolotls can regrow entire lost limbs, including bones, muscles and nerves." },
  { word: "Platypus", fact: "The platypus is one of the only mammals that lays eggs instead of giving live birth." },
  { word: "Naked Mole Rat", fact: "Naked mole rats can survive for long periods with almost no oxygen and rarely develop cancer." },
  { word: "Tardigrades", fact: "Tardigrades can survive the vacuum of space and doses of radiation that would kill most animals." },
  { word: "Immortal Jellyfish", fact: "The Turritopsis dohrnii jellyfish can revert its cells to an earlier life stage, effectively restarting its life cycle." },
  { word: "Blue Whale", fact: "The blue whale is the largest animal known to have ever lived, larger than any dinosaur." },
  { word: "Hippos", fact: "Hippos secrete a reddish fluid from their skin that acts as a natural sunscreen." },
  { word: "Narwhal", fact: "The narwhal's long tusk is actually an enlarged tooth that spirals out through its upper lip." },
  { word: "Seahorses", fact: "In seahorses, the male carries the developing young in a pouch and gives birth to them." },
  { word: "Electric Eel", fact: "An electric eel can generate a shock of several hundred volts to stun its prey." },
  { word: "Cuttlefish", fact: "Cuttlefish have blue-green blood because it uses copper instead of iron to carry oxygen." },
  { word: "Pistol Shrimp", fact: "A pistol shrimp snaps its claw so fast it creates a bubble that briefly reaches temperatures near that of the Sun's surface." },
  { word: "Reindeer", fact: "Reindeer eyes change color between summer and winter, shifting from gold to blue." },
  { word: "Arctic Tern", fact: "The Arctic tern migrates from the Arctic to the Antarctic and back each year, the longest known migration of any animal." },
  { word: "Emperor Dragonfly", fact: "Dragonflies have nearly 360-degree vision thanks to compound eyes with thousands of lenses." },
  { word: "Cicadas", fact: "Some cicada species stay underground as nymphs for 13 or 17 years before emerging all at once." },
  { word: "Firefly", fact: "Fireflies produce light through a chemical reaction that gives off almost no heat, called bioluminescence." },
  { word: "Peacock Mantis", fact: "Mantis shrimp have more types of color-receptor cells in their eyes than humans do." },
  { word: "Komodo Dragon", fact: "The Komodo dragon is the largest living species of lizard, reaching up to three meters long." },
  { word: "Alligators", fact: "The sex of many alligators is determined by the temperature at which their eggs incubate." },
  { word: "Vampire Bat", fact: "Vampire bats will share regurgitated blood meals with roost-mates that failed to feed." },
  { word: "Tasmanian Devil", fact: "Tasmanian devils have one of the strongest bites relative to body size of any living mammal." },
  { word: "Pangolin", fact: "The pangolin is the only mammal fully covered in true scales made of keratin." },
  { word: "Corvids", fact: "Crows and ravens can recognize individual human faces and hold grudges against them." },
  { word: "Octopus Skin", fact: "Octopuses can taste and detect chemicals through the suckers on their arms." },
  { word: "Manatees", fact: "Manatees are more closely related to elephants than to other marine mammals." },
  { word: "Bombardier Beetle", fact: "The bombardier beetle sprays a boiling, chemically explosive liquid at attackers from its abdomen." },
  { word: "Venus Flytrap", fact: "A Venus flytrap counts touches on its trigger hairs before snapping shut, needing two within seconds." },
  { word: "Pitcher Plant", fact: "Pitcher plants trap and digest insects inside a slippery, fluid-filled cavity." },
  { word: "Corpse Flower", fact: "The titan arum, or corpse flower, smells of rotting flesh to attract pollinating insects." },
  { word: "Mimosa Plant", fact: "The leaves of the Mimosa pudica plant fold up within seconds when touched." },
  { word: "Aspen Grove", fact: "A single aspen grove named Pando is a clonal colony that shares one enormous root system." },
  { word: "Baobab", fact: "Baobab trees can store thousands of liters of water inside their swollen trunks." },
  { word: "Ginkgo", fact: "The ginkgo is a living fossil, a tree species that has existed largely unchanged for over 200 million years." },
  { word: "Sequoia", fact: "Giant sequoias are the largest trees by volume, though they are not the tallest." },
  { word: "Mushrooms", fact: "The largest known living organism is a honey fungus in Oregon spanning several square kilometers underground." },
  { word: "Lichen", fact: "A lichen is not a single organism but a partnership between a fungus and an alga or cyanobacterium." },
  { word: "Nettles", fact: "Stinging nettles inject a mix of chemicals through tiny hollow hairs that break on contact with skin." },
  { word: "Helium", fact: "Helium was first detected in the Sun's spectrum before it was ever found on Earth." },
  { word: "Neutron Star", fact: "A teaspoon of neutron star material would weigh billions of tons on Earth." },
  { word: "Bones", fact: "The human femur, or thigh bone, is stronger than concrete under compression." },
  { word: "Sound", fact: "Sound travels roughly four times faster through water than through air." },
  { word: "Oxygen", fact: "Liquid oxygen is pale blue in color, not clear like water." },
  { word: "The Sun", fact: "Light from the Sun takes about eight minutes to reach the Earth." },
  { word: "Bacteria", fact: "The human body contains roughly as many bacterial cells as it does human cells." },
  { word: "Absolute Zero", fact: "Absolute zero, the coldest possible temperature, is about minus 273 degrees Celsius." },
  { word: "Mars", fact: "Mars is home to the tallest known volcano in the solar system, Olympus Mons." },
  { word: "Gold", fact: "Gold is so unreactive that it can be found in nature as a pure metal rather than as an ore." },
  { word: "Skin", fact: "The skin is the largest organ of the human body." },
  { word: "Black Hole", fact: "Not even light can escape from beyond the event horizon of a black hole." },
  { word: "Diamond", fact: "Diamond and graphite are both made entirely of carbon atoms." },
  { word: "Nerves", fact: "Nerve signals in the human body can travel faster than 100 meters per second." },
  { word: "Vacuum", fact: "In a vacuum, a feather and a hammer fall at exactly the same rate." },
  { word: "Mercury Metal", fact: "Mercury is the only metal that is liquid at ordinary room temperature." },
  { word: "Saliva", fact: "A person produces enough saliva over a lifetime to fill several bathtubs." },
  { word: "The Milky Way", fact: "The Milky Way galaxy contains hundreds of billions of stars." },
  { word: "Water", fact: "Water expands and becomes less dense when it freezes, which is why ice floats." },
  { word: "Blood", fact: "Blood makes up roughly 7 to 8 percent of an adult human's body weight." },
  { word: "Sound Barrier", fact: "The crack of a whip is a small sonic boom caused by the tip breaking the sound barrier." },
  { word: "Comets", fact: "A comet's tail always points away from the Sun, no matter which way the comet is moving." },
  { word: "Hydrogen", fact: "Hydrogen is the most abundant element in the entire universe." },
  { word: "Fingernails", fact: "Fingernails grow noticeably faster than toenails." },
  { word: "The Kelvin Scale", fact: "The Kelvin temperature scale has no negative numbers because it starts at absolute zero." },
  { word: "Titanium", fact: "Titanium is nearly as strong as steel but roughly 45 percent lighter." },
  { word: "The Heart", fact: "The human heart beats around 100,000 times in a single day." },
  { word: "Antimatter", fact: "When matter meets its antimatter counterpart, both are annihilated and converted into energy." },
  { word: "Static Electricity", fact: "A bolt of static electricity from your finger can reach several thousand volts." },
  { word: "Sodium", fact: "Pure sodium reacts violently with water, fizzing and sometimes bursting into flame." },
  { word: "The Appendix", fact: "A person can live a completely normal life after having their appendix removed." },
  { word: "Light Year", fact: "A light year measures distance, not time, equal to how far light travels in one year." },
  { word: "Rust", fact: "Rust forms when iron reacts with oxygen and moisture in the air." },
  { word: "Taste Buds", fact: "Humans can detect five basic tastes: sweet, sour, salty, bitter, and umami." },
  { word: "Nitrogen", fact: "Nitrogen makes up about 78 percent of the air we breathe." },
  { word: "Goosebumps", fact: "Goosebumps are caused by tiny muscles pulling on the base of each body hair." },
  { word: "The Speed of Light", fact: "Nothing with mass can reach or exceed the speed of light in a vacuum." },
  { word: "Ferris Wheel", fact: "The first Ferris wheel debuted at the 1893 World's Fair in Chicago." },
  { word: "Canada", fact: "Canada has more lakes than the rest of the world's countries combined." },
  { word: "Ancient Egypt", fact: "Ancient Egyptians used a paste of ground pumice and vinegar as an early form of toothpaste." },
  { word: "Russia", fact: "Russia spans eleven time zones, more than any other country." },
  { word: "Popsicle", fact: "The popsicle was invented by an 11-year-old boy who left a drink with a stirring stick outside overnight." },
  { word: "The Great Fire of London", fact: "The Great Fire of London in 1666 destroyed most of the medieval city but killed very few people officially recorded." },
  { word: "France", fact: "France was the most visited country in the world by international tourist arrivals for many years running." },
  { word: "Pizza Margherita", fact: "Pizza Margherita is said to be named after Queen Margherita of Savoy, its colors matching the Italian flag." },
  { word: "Umbrella", fact: "Umbrellas were used for shade from the sun long before they were adapted to keep off rain." },
  { word: "The Berlin Wall", fact: "The Berlin Wall stood for 28 years before it fell in 1989." },
  { word: "Monaco", fact: "Monaco is the second smallest independent country in the world after Vatican City." },
  { word: "Croissant", fact: "The croissant is widely believed to have originated in Austria rather than France." },
  { word: "Velcro", fact: "Velcro was inspired by the way burrs stuck to a dog's fur during a walk." },
  { word: "The Colosseum", fact: "The Roman Colosseum could hold an estimated 50,000 or more spectators." },
  { word: "Japan", fact: "Japan is made up of thousands of islands, numbering in the many thousands." },
  { word: "Ice Cream Cone", fact: "The edible ice cream cone gained wide popularity at the 1904 World's Fair in St. Louis." },
  { word: "Zipper", fact: "The zipper was originally marketed under a different name before the word zipper caught on." },
  { word: "The Titanic", fact: "The Titanic sank on its maiden voyage in 1912 after striking an iceberg." },
  { word: "Chile", fact: "Chile is one of the longest and narrowest countries in the world, stretching more than 4,000 kilometers north to south." },
  { word: "Pretzel", fact: "The pretzel's twisted shape is traditionally said to represent arms folded in prayer." },
  { word: "Microwave Oven", fact: "The microwave oven was invented after an engineer noticed a chocolate bar melting in his pocket near radar equipment." },
  { word: "The Rosetta Stone", fact: "The Rosetta Stone was key to deciphering Egyptian hieroglyphs because it repeats the same text in three scripts." },
  { word: "Norway", fact: "Norway's coastline is dramatically lengthened by its many fjords." },
  { word: "Sandwich", fact: "The sandwich is named after the Earl of Sandwich, an 18th-century English nobleman." },
  { word: "Toothbrush", fact: "The first mass-produced toothbrushes used bristles made from animal hair." },
  { word: "The Leaning Tower of Pisa", fact: "The Leaning Tower of Pisa began to tilt during its construction because of soft ground." },
  { word: "Brazil", fact: "Brazil is the only country in the Americas where Portuguese is the official language." },
  { word: "Sushi", fact: "Sushi originally referred to a method of preserving fish in fermented rice, not the fresh dish known today." },
  { word: "Safety Pin", fact: "The modern safety pin was patented in the mid-1800s by Walter Hunt." },
  { word: "Pompeii", fact: "The city of Pompeii was buried and preserved by ash after the eruption of Mount Vesuvius in 79 AD." },
  { word: "Switzerland", fact: "Switzerland has four official national languages." },
  { word: "Chocolate", fact: "Chocolate comes from the fermented and roasted seeds of the cacao tree." },
  { word: "Post-it Notes", fact: "Post-it Notes came from a weak adhesive that was originally considered a failed experiment." },
  { word: "The Panama Canal", fact: "The Panama Canal uses a system of locks to raise and lower ships between different water levels." },
  { word: "Finland", fact: "Finland is often nicknamed the land of a thousand lakes, though it actually has far more than that." },
  { word: "Ballpoint Pen", fact: "The ballpoint pen was developed to write more smoothly and dry faster than a fountain pen." },
];

/** Draw a random card, optionally excluding words already used this game so the
 *  same fact doesn't recur within a single room session. Falls back to the full
 *  deck once every card has been seen. */
export function drawRandomCard(usedWords: string[] = []): PokerFaceCard {
  const used = new Set(usedWords);
  const fresh = POKERFACE_CARDS.filter((c) => !used.has(c.word));
  const pool = fresh.length > 0 ? fresh : POKERFACE_CARDS;
  return pool[Math.floor(Math.random() * pool.length)];
}
