// lib/party/word-lists.ts
// Curated word pools for Lionade Party — Sketchy Subjects.
// Each entry: { word, difficulty, factoid }
// Used by /api/party/sketch/rounds when picking candidate words.
// Source of truth for the party_word_lists table seed.

export type WordEntry = {
  word: string;
  difficulty: "easy" | "medium" | "hard";
  factoid: string;
};

export type PartySubject =
  | "biology"
  | "chemistry"
  | "physics"
  | "math"
  | "history"
  | "geography"
  | "astronomy"
  | "pop-culture";

export const WORD_LISTS: Record<PartySubject, WordEntry[]> = {
  biology: [
    { word: "cell", difficulty: "easy", factoid: "Your body builds about 330 billion new cells every single day to replace old ones." },
    { word: "heart", difficulty: "easy", factoid: "A human heart beats about 100,000 times a day without ever needing a break." },
    { word: "brain", difficulty: "easy", factoid: "The human brain uses around 20 percent of your body's total energy at rest." },
    { word: "lungs", difficulty: "easy", factoid: "If you flattened out your lungs, they'd cover roughly the size of a tennis court." },
    { word: "skeleton", difficulty: "easy", factoid: "Babies are born with about 270 bones, but adults only have 206 once some fuse together." },
    { word: "tooth", difficulty: "easy", factoid: "Tooth enamel is the hardest substance in the human body, harder than bone." },
    { word: "eye", difficulty: "easy", factoid: "Your eyes can distinguish about 10 million different colors." },
    { word: "tongue", difficulty: "easy", factoid: "Every tongue has a unique print, just like a fingerprint." },
    { word: "blood", difficulty: "easy", factoid: "An adult body contains roughly 1.5 gallons of blood, recycled through the heart every minute." },
    { word: "skin", difficulty: "easy", factoid: "Skin is the body's largest organ and you shed about 40,000 cells of it every hour." },
    { word: "leaf", difficulty: "easy", factoid: "Leaves change color in fall because they stop making green chlorophyll, revealing pigments that were there all along." },
    { word: "flower", difficulty: "easy", factoid: "Sunflowers track the sun across the sky when they're young, a behavior called heliotropism." },
    { word: "tree", difficulty: "easy", factoid: "The oldest known tree, a bristlecone pine named Methuselah, is over 4,800 years old." },
    { word: "bone", difficulty: "easy", factoid: "Bones are about five times stronger than steel of the same weight." },
    { word: "muscle", difficulty: "easy", factoid: "The strongest muscle in your body, by force, is the masseter, the one in your jaw." },
    { word: "spider", difficulty: "easy", factoid: "Spider silk is, weight for weight, stronger than steel and tougher than Kevlar." },
    { word: "butterfly", difficulty: "easy", factoid: "Butterflies taste with their feet so they can tell if a leaf is good for laying eggs." },
    { word: "frog", difficulty: "easy", factoid: "Frogs absorb water through their skin instead of drinking it." },
    { word: "ant", difficulty: "easy", factoid: "Ants can lift up to 50 times their own body weight thanks to their tiny size and dense muscles." },
    { word: "fish", difficulty: "easy", factoid: "Most fish have a sixth sense called the lateral line that detects water vibrations." },
    { word: "DNA", difficulty: "medium", factoid: "If you unwound all the DNA in your body, it would stretch to the sun and back over 300 times." },
    { word: "neuron", difficulty: "medium", factoid: "Signals between neurons can travel up to 268 miles per hour." },
    { word: "virus", difficulty: "medium", factoid: "Viruses aren't technically alive, they can't reproduce without hijacking a host cell." },
    { word: "bacteria", difficulty: "medium", factoid: "You have more bacterial cells in and on your body than human cells." },
    { word: "mitochondria", difficulty: "medium", factoid: "Mitochondria have their own DNA, inherited only from your mother." },
    { word: "ribosome", difficulty: "medium", factoid: "Ribosomes build proteins by reading messenger RNA at about 20 amino acids per second." },
    { word: "chloroplast", difficulty: "medium", factoid: "Chloroplasts were once free-living bacteria that got absorbed by ancient plant ancestors." },
    { word: "photosynthesis", difficulty: "medium", factoid: "Photosynthesis is responsible for nearly all the oxygen in Earth's atmosphere." },
    { word: "antibody", difficulty: "medium", factoid: "Your body can produce roughly 10 billion unique antibody shapes to fight invaders." },
    { word: "enzyme", difficulty: "medium", factoid: "Some enzymes speed up chemical reactions by a factor of a trillion." },
    { word: "hormone", difficulty: "medium", factoid: "Adrenaline can hit your bloodstream in less than a second when you're startled." },
    { word: "embryo", difficulty: "medium", factoid: "A human embryo briefly has a tail in early development before it gets reabsorbed." },
    { word: "fungus", difficulty: "medium", factoid: "The largest organism on Earth is a honey fungus in Oregon, covering 2,385 acres." },
    { word: "jellyfish", difficulty: "medium", factoid: "Jellyfish have no brain, no heart, and no bones, they're 95 percent water." },
    { word: "octopus", difficulty: "medium", factoid: "Octopuses have three hearts and blue blood thanks to copper-based hemoglobin." },
    { word: "kangaroo", difficulty: "medium", factoid: "Kangaroos can't walk backwards, which is partly why they're on Australia's coat of arms." },
    { word: "platypus", difficulty: "medium", factoid: "Male platypuses have venomous spurs on their hind legs, one of the few venomous mammals." },
    { word: "chromosome", difficulty: "medium", factoid: "Humans share about 60 percent of their genes with bananas." },
    { word: "stomach", difficulty: "medium", factoid: "Your stomach lining replaces itself every 3 to 4 days to avoid digesting itself." },
    { word: "liver", difficulty: "medium", factoid: "The liver is the only human organ that can fully regenerate from as little as 25 percent of itself." },
    { word: "tardigrade", difficulty: "hard", factoid: "Tardigrades can survive being boiled, frozen, irradiated, and even shot into space." },
    { word: "mycelium", difficulty: "hard", factoid: "Mycelium networks let trees in a forest share nutrients and warning signals underground." },
    { word: "axon", difficulty: "hard", factoid: "The longest axon in your body runs from the base of your spine to your big toe." },
    { word: "amoeba", difficulty: "hard", factoid: "Amoebas hunt by changing shape and engulfing their prey whole." },
    { word: "paramecium", difficulty: "hard", factoid: "A single paramecium is covered in thousands of tiny hairs that beat like oars to swim." },
    { word: "venus flytrap", difficulty: "hard", factoid: "A Venus flytrap only snaps shut after two hairs are touched within 20 seconds, to avoid wasting energy on raindrops." },
    { word: "stem cell", difficulty: "hard", factoid: "A single stem cell can theoretically grow into any of the 200+ cell types in your body." },
    { word: "synapse", difficulty: "hard", factoid: "Your brain has about 100 trillion synapses, more than there are stars in the Milky Way." },
    { word: "golgi apparatus", difficulty: "hard", factoid: "The Golgi apparatus packages proteins for shipping like a microscopic post office." },
    { word: "nucleus", difficulty: "hard", factoid: "If a cell were the size of a city, its nucleus would be the city hall with all the blueprints inside." },
  ],

  chemistry: [
    { word: "atom", difficulty: "easy", factoid: "Atoms are mostly empty space, if a nucleus were a marble, the electrons would orbit kilometers away." },
    { word: "water", difficulty: "easy", factoid: "Water is one of the only substances that expands when it freezes, which is why ice floats." },
    { word: "salt", difficulty: "easy", factoid: "Table salt is a crystal of sodium and chlorine, both of which are deadly on their own." },
    { word: "fire", difficulty: "easy", factoid: "Fire has no fixed shape because it's plasma, a fourth state of matter, not solid, liquid, or gas." },
    { word: "ice", difficulty: "easy", factoid: "There are at least 19 different known crystalline structures of ice, depending on temperature and pressure." },
    { word: "gold", difficulty: "easy", factoid: "All the gold ever mined would fit into a cube about 22 meters on each side." },
    { word: "iron", difficulty: "easy", factoid: "The iron in your blood was forged inside an exploding star billions of years ago." },
    { word: "oxygen", difficulty: "easy", factoid: "Oxygen makes up about 21 percent of the air you breathe, but 65 percent of your body weight." },
    { word: "hydrogen", difficulty: "easy", factoid: "Hydrogen is the most abundant element in the universe, making up roughly 75 percent of all matter." },
    { word: "rust", difficulty: "easy", factoid: "Rust is iron slowly reacting with oxygen, basically iron burning in slow motion." },
    { word: "soap", difficulty: "easy", factoid: "Soap works by grabbing oil with one end and water with the other, so dirt washes away." },
    { word: "battery", difficulty: "easy", factoid: "The first battery was a stack of zinc and copper disks invented by Alessandro Volta in 1800." },
    { word: "balloon", difficulty: "easy", factoid: "Helium balloons float because helium is about seven times lighter than air." },
    { word: "candle", difficulty: "easy", factoid: "A candle flame is hot enough to melt steel at its hottest point, around 1,400 degrees Celsius." },
    { word: "rubber", difficulty: "easy", factoid: "Natural rubber comes from the milky sap of the Para rubber tree, harvested like maple syrup." },
    { word: "glass", difficulty: "easy", factoid: "Glass isn't really a solid or a liquid, it's an amorphous solid, frozen in mid-flow." },
    { word: "beaker", difficulty: "easy", factoid: "The flat-bottomed beaker was popularized by chemist John Griffin in the 1800s." },
    { word: "magnet", difficulty: "easy", factoid: "Magnets work because billions of tiny electron spins inside the metal all line up the same way." },
    { word: "molecule", difficulty: "medium", factoid: "A single drop of water contains about 1.5 sextillion water molecules." },
    { word: "electron", difficulty: "medium", factoid: "Electrons don't actually orbit the nucleus, they exist as fuzzy probability clouds." },
    { word: "proton", difficulty: "medium", factoid: "The number of protons in an atom is what decides which element it is." },
    { word: "neutron", difficulty: "medium", factoid: "A free neutron outside an atomic nucleus only lives for about 15 minutes before decaying." },
    { word: "acid", difficulty: "medium", factoid: "Your stomach acid is strong enough to dissolve a razor blade in about a week." },
    { word: "base", difficulty: "medium", factoid: "Bleach is a strong base, which is why it feels slippery on your skin, it's dissolving the oils." },
    { word: "periodic table", difficulty: "medium", factoid: "Dmitri Mendeleev left gaps in his 1869 periodic table to predict elements not yet discovered." },
    { word: "covalent bond", difficulty: "medium", factoid: "In a covalent bond, atoms share electrons like two people sharing the same blanket." },
    { word: "ionic bond", difficulty: "medium", factoid: "Ionic bonds form when one atom basically steals an electron from another atom." },
    { word: "crystal", difficulty: "medium", factoid: "Snowflakes are crystals, and no two are exactly alike because of tiny differences in their fall path." },
    { word: "carbon", difficulty: "medium", factoid: "Diamonds and pencil graphite are both pure carbon, just arranged differently." },
    { word: "diamond", difficulty: "medium", factoid: "It takes about a billion years deep underground to form a natural diamond." },
    { word: "copper", difficulty: "medium", factoid: "Copper turns green over time because it reacts with air to form a layer called verdigris." },
    { word: "mercury", difficulty: "medium", factoid: "Mercury is the only metal that's a liquid at room temperature." },
    { word: "helium", difficulty: "medium", factoid: "Helium was first discovered in the sun's atmosphere before anyone found it on Earth." },
    { word: "neon", difficulty: "medium", factoid: "Neon glows orange-red when electricity runs through it; other colors in 'neon signs' use different gases." },
    { word: "uranium", difficulty: "medium", factoid: "A single uranium fuel pellet the size of a fingertip holds the energy of a ton of coal." },
    { word: "test tube", difficulty: "medium", factoid: "The standard test tube was popularized by Michael Faraday in the 1820s." },
    { word: "Bunsen burner", difficulty: "medium", factoid: "Robert Bunsen didn't actually invent the Bunsen burner, his assistant Peter Desaga built it." },
    { word: "litmus paper", difficulty: "medium", factoid: "Litmus paper is dyed with a pigment extracted from lichens." },
    { word: "polymer", difficulty: "medium", factoid: "Plastic, DNA, and silk are all polymers, long chains of repeating molecular units." },
    { word: "alloy", difficulty: "medium", factoid: "Steel is an alloy of iron and carbon, and even a tiny bit of carbon makes iron dramatically stronger." },
    { word: "graphene", difficulty: "hard", factoid: "Graphene is one atom thick, yet 200 times stronger than steel." },
    { word: "isotope", difficulty: "hard", factoid: "Carbon-14 dating uses a radioactive isotope of carbon to figure out the age of old bones and wood." },
    { word: "catalyst", difficulty: "hard", factoid: "Platinum catalysts in car exhausts turn toxic gases into harmless ones in milliseconds." },
    { word: "fullerene", difficulty: "hard", factoid: "The molecule C60, nicknamed buckyball, is shaped exactly like a soccer ball." },
    { word: "noble gas", difficulty: "hard", factoid: "Noble gases like argon and xenon rarely react with anything because their electron shells are full." },
    { word: "centrifuge", difficulty: "hard", factoid: "Lab centrifuges can spin at over 100,000 RPM to separate molecules by weight." },
    { word: "titration", difficulty: "hard", factoid: "Careful titration can measure chemical concentrations down to a hundredth of a percent." },
    { word: "plasma", difficulty: "hard", factoid: "Plasma is the most common state of matter in the universe, every star is made of it." },
    { word: "buffer", difficulty: "hard", factoid: "Your blood is a chemical buffer that holds its pH between 7.35 and 7.45 no matter what you eat." },
    { word: "ester", difficulty: "hard", factoid: "Many fruit smells, like banana and pineapple, come from ester molecules." },
  ],

  physics: [
    { word: "gravity", difficulty: "easy", factoid: "Gravity on the moon is about one-sixth of Earth's, which is why astronauts bounce when they walk." },
    { word: "magnet", difficulty: "easy", factoid: "Earth itself is a giant magnet, which is why compass needles always point north." },
    { word: "rainbow", difficulty: "easy", factoid: "A rainbow is actually a full circle, you only see a half-arc because the ground gets in the way." },
    { word: "lightning", difficulty: "easy", factoid: "A lightning bolt can hit nearly 30,000 degrees Celsius, about five times hotter than the sun's surface." },
    { word: "spring", difficulty: "easy", factoid: "The bigger the spring's stretch, the bigger the force pulling it back, that's Hooke's Law." },
    { word: "lever", difficulty: "easy", factoid: "Archimedes once said give him a long enough lever and he could move the entire Earth." },
    { word: "pulley", difficulty: "easy", factoid: "A simple pulley doesn't multiply force, but combinations of pulleys let one person lift cars." },
    { word: "wheel", difficulty: "easy", factoid: "The wheel was invented around 3500 BCE, but mostly used for pottery before it ever became transportation." },
    { word: "ramp", difficulty: "easy", factoid: "A ramp is one of the six classical simple machines, ancient Egyptians used them to build pyramids." },
    { word: "screw", difficulty: "easy", factoid: "Archimedes' screw, invented over 2,000 years ago, is still used today to lift water on farms." },
    { word: "mirror", difficulty: "easy", factoid: "Even the cleanest mirrors only reflect about 95 percent of the light that hits them." },
    { word: "prism", difficulty: "easy", factoid: "Isaac Newton used a prism in 1666 to prove that white light is made of every color mixed together." },
    { word: "lens", difficulty: "easy", factoid: "Eyeglasses were invented in Italy around 1290, but for nearly 300 years they only helped with reading." },
    { word: "shadow", difficulty: "easy", factoid: "A shadow has no actual substance, it's just an absence of light." },
    { word: "echo", difficulty: "easy", factoid: "An echo only works if there's at least 17 meters between you and the wall, closer and your ear blends them." },
    { word: "fan", difficulty: "easy", factoid: "A fan doesn't cool a room, it just moves air to help sweat evaporate off your skin." },
    { word: "balloon", difficulty: "easy", factoid: "Rubbing a balloon on your hair gives it a static charge, that's a few trillion extra electrons." },
    { word: "pendulum", difficulty: "easy", factoid: "Galileo discovered that a pendulum's swing time depends on its length, not how heavy the weight is." },
    { word: "wave", difficulty: "medium", factoid: "Sound waves travel about four times faster through water than through air." },
    { word: "friction", difficulty: "medium", factoid: "Without friction, you couldn't walk, write, or hold anything, everything would slide endlessly." },
    { word: "force", difficulty: "medium", factoid: "One Newton of force is roughly the weight of a small apple in your hand." },
    { word: "voltage", difficulty: "medium", factoid: "A static shock from a doorknob can carry 10,000 volts, but barely any current, that's why it doesn't hurt much." },
    { word: "circuit", difficulty: "medium", factoid: "A simple light bulb circuit was first demonstrated by Humphry Davy in 1802, decades before Edison." },
    { word: "electromagnet", difficulty: "medium", factoid: "An electromagnet only stays magnetic while electricity flows through it, flip the switch and it lets go." },
    { word: "transformer", difficulty: "medium", factoid: "Transformers on power lines step voltage up to hundreds of thousands of volts to move energy over long distances." },
    { word: "telescope", difficulty: "medium", factoid: "Galileo's first telescope in 1609 magnified objects only 3 times, modern ones magnify over 1,000." },
    { word: "microscope", difficulty: "medium", factoid: "Antonie van Leeuwenhoek built single-lens microscopes in the 1670s that could already see bacteria." },
    { word: "fulcrum", difficulty: "medium", factoid: "Move the fulcrum closer to the load and you can lift huge weights with very little effort." },
    { word: "gear", difficulty: "medium", factoid: "A bicycle's gears trade speed for force, small gear pedaling lets you climb steep hills." },
    { word: "battery", difficulty: "medium", factoid: "Inside a battery, a slow chemical reaction shuffles electrons through your device." },
    { word: "magnifying glass", difficulty: "medium", factoid: "A magnifying glass works the same way a single-lens telescope does, bending light to fake closeness." },
    { word: "compass", difficulty: "medium", factoid: "The magnetic compass was invented in China around 200 BCE, originally for fortune-telling, not navigation." },
    { word: "kite", difficulty: "medium", factoid: "Ben Franklin's 1752 kite experiment proved lightning is electricity, and almost killed him." },
    { word: "rocket", difficulty: "medium", factoid: "A rocket works by Newton's third law, throw mass one way fast enough and you're shoved the other way." },
    { word: "spring scale", difficulty: "medium", factoid: "Spring scales were invented around 1770 by Richard Salter, an English balance maker." },
    { word: "tuning fork", difficulty: "medium", factoid: "Tuning forks were invented in 1711 and have been used to set musical pitch ever since." },
    { word: "laser", difficulty: "medium", factoid: "Laser stands for Light Amplification by Stimulated Emission of Radiation." },
    { word: "fiber optic", difficulty: "medium", factoid: "Light bounces inside a hair-thin glass fiber thousands of times per kilometer to deliver your internet." },
    { word: "gyroscope", difficulty: "hard", factoid: "Gyroscopes keep airplanes and phones oriented because spinning objects resist changing direction." },
    { word: "capacitor", difficulty: "hard", factoid: "A capacitor stores charge in seconds and dumps it almost instantly, camera flashes use them." },
    { word: "wormhole", difficulty: "hard", factoid: "Wormholes are theoretical shortcuts through spacetime predicted by Einstein's equations, but none have been found." },
    { word: "diffraction", difficulty: "hard", factoid: "Light bends around tiny edges, that's why a CD's surface fans out into rainbow colors." },
    { word: "superconductor", difficulty: "hard", factoid: "Superconductors carry electricity with literally zero resistance, but most only work near absolute zero." },
    { word: "particle accelerator", difficulty: "hard", factoid: "The Large Hadron Collider smashes protons together at 99.9999991 percent the speed of light." },
    { word: "doppler effect", difficulty: "hard", factoid: "The Doppler effect is why an ambulance siren sounds higher coming toward you and lower as it leaves." },
    { word: "torque", difficulty: "hard", factoid: "Torque, not horsepower, is what lets a truck pull a heavy trailer up a hill." },
    { word: "centrifuge", difficulty: "hard", factoid: "Astronaut training centrifuges spin pilots at up to 9 Gs to simulate intense acceleration." },
    { word: "quark", difficulty: "hard", factoid: "Quarks come in flavors called up, down, charm, strange, top, and bottom." },
    { word: "neutrino", difficulty: "hard", factoid: "About 65 billion neutrinos pass through every square centimeter of you every second from the sun." },
    { word: "antimatter", difficulty: "hard", factoid: "When antimatter meets regular matter, both vanish in a flash of pure energy." },
  ],

  math: [
    { word: "circle", difficulty: "easy", factoid: "A circle is the only shape with infinite lines of symmetry." },
    { word: "triangle", difficulty: "easy", factoid: "Triangles are the strongest shape in engineering because they can't deform without breaking." },
    { word: "square", difficulty: "easy", factoid: "A square is a special rectangle and a special rhombus at the same time." },
    { word: "cube", difficulty: "easy", factoid: "A cube has 6 faces, 12 edges, and 8 corners, Euler's formula confirms 6 minus 12 plus 8 equals 2." },
    { word: "sphere", difficulty: "easy", factoid: "A sphere holds the most volume for the least surface area, which is why bubbles are round." },
    { word: "pyramid", difficulty: "easy", factoid: "A square pyramid has 5 faces, including the bottom." },
    { word: "fraction", difficulty: "easy", factoid: "Ancient Egyptians wrote almost all fractions as sums of fractions with 1 on top." },
    { word: "ruler", difficulty: "easy", factoid: "The standard 30-centimeter ruler became common only after metric system reforms in 1799." },
    { word: "protractor", difficulty: "easy", factoid: "Protractors trace back to 13th-century star charts used by sailors." },
    { word: "compass", difficulty: "easy", factoid: "Geometry compasses go back to ancient Greece, used by Euclid himself around 300 BCE." },
    { word: "abacus", difficulty: "easy", factoid: "Skilled abacus users can sometimes calculate faster than people with calculators." },
    { word: "dice", difficulty: "easy", factoid: "On a standard die, opposite faces always add up to 7." },
    { word: "clock", difficulty: "easy", factoid: "Old clocks used Roman numerals for hours, where 4 was written IIII instead of IV for visual balance." },
    { word: "graph", difficulty: "easy", factoid: "Rene Descartes invented the coordinate graph while watching a fly walk across his ceiling." },
    { word: "angle", difficulty: "easy", factoid: "The sum of angles inside any triangle is always exactly 180 degrees on a flat surface." },
    { word: "line", difficulty: "easy", factoid: "In math, a line goes on forever in both directions; if it stops, it's a line segment." },
    { word: "pi", difficulty: "easy", factoid: "Pi has been calculated to over 100 trillion digits, but only 39 are needed to measure the universe to atomic precision." },
    { word: "infinity", difficulty: "easy", factoid: "Some infinities are bigger than others; the infinity of real numbers is larger than the infinity of integers." },
    { word: "octagon", difficulty: "easy", factoid: "Stop signs are octagons in nearly every country, an idea standardized in 1954." },
    { word: "hexagon", difficulty: "easy", factoid: "Bees build hexagonal honeycombs because hexagons use the least wax for the most storage." },
    { word: "vector", difficulty: "medium", factoid: "Vectors have both a size and a direction, which is why GPS uses them to plot your route." },
    { word: "matrix", difficulty: "medium", factoid: "Computer graphics use 4 by 4 matrices to rotate, scale, and move every 3D object on screen." },
    { word: "set", difficulty: "medium", factoid: "Modern set theory was built by Georg Cantor in the 1870s, and it shocked mathematicians of his time." },
    { word: "theorem", difficulty: "medium", factoid: "The Pythagorean theorem was known to the Babylonians a thousand years before Pythagoras." },
    { word: "function", difficulty: "medium", factoid: "Mathematical functions are basically recipes, you put a number in, you get exactly one number out." },
    { word: "equation", difficulty: "medium", factoid: "The equals sign was invented in 1557 by Robert Recorde because he got tired of writing 'is equal to'." },
    { word: "parabola", difficulty: "medium", factoid: "Throw any object and its path is a parabola, that's why satellite dishes are parabola-shaped." },
    { word: "ellipse", difficulty: "medium", factoid: "Planet orbits are ellipses, not perfect circles, as Johannes Kepler proved in 1609." },
    { word: "hyperbola", difficulty: "medium", factoid: "Cooling towers at power plants are shaped like hyperbolas for structural strength." },
    { word: "logarithm", difficulty: "medium", factoid: "Logarithms were invented in 1614 by John Napier to make astronomical math easier." },
    { word: "exponent", difficulty: "medium", factoid: "A chessboard with 1 grain of rice doubling each square ends up holding more rice than the world produces in a year." },
    { word: "polygon", difficulty: "medium", factoid: "Regular polygons with more sides look more like circles, until they basically are circles." },
    { word: "prism", difficulty: "medium", factoid: "A geometric prism has two identical ends connected by flat sides, Toblerone bars are triangular prisms." },
    { word: "tangent", difficulty: "medium", factoid: "A tangent line touches a curve at exactly one point, no more, no less." },
    { word: "symmetry", difficulty: "medium", factoid: "The human face is famously slightly asymmetrical, which is part of what we read as character." },
    { word: "factorial", difficulty: "medium", factoid: "52 factorial, the ways to shuffle a deck, is so large no two well-shuffled decks in history have likely matched." },
    { word: "median", difficulty: "medium", factoid: "The median is the middle value in a list, which is why home-price reports prefer it to the average." },
    { word: "probability", difficulty: "medium", factoid: "The probability of being struck by lightning in your lifetime in the US is about 1 in 15,000." },
    { word: "integral", difficulty: "hard", factoid: "Integrals add up infinite tiny slices, which is how engineers compute the area under any curve." },
    { word: "derivative", difficulty: "hard", factoid: "A derivative tells you the instant slope of a curve, Newton invented this to describe motion." },
    { word: "fractal", difficulty: "hard", factoid: "Fractals repeat the same pattern at every zoom level, broccoli and coastlines are real-world examples." },
    { word: "mobius strip", difficulty: "hard", factoid: "A Mobius strip is a loop with only one side and one edge, try drawing a line down it without lifting your pen." },
    { word: "torus", difficulty: "hard", factoid: "A donut is a torus, and topologically a coffee mug is the same shape, one hole each." },
    { word: "vertex", difficulty: "hard", factoid: "Every corner of a polygon is called a vertex; the plural is vertices." },
    { word: "asymptote", difficulty: "hard", factoid: "An asymptote is a line a curve gets arbitrarily close to but never actually touches." },
    { word: "tetrahedron", difficulty: "hard", factoid: "A tetrahedron has 4 faces, all triangles, and is the simplest 3D shape with flat sides." },
    { word: "dodecahedron", difficulty: "hard", factoid: "A dodecahedron has 12 pentagonal faces, Plato linked this shape to the cosmos itself." },
    { word: "permutation", difficulty: "hard", factoid: "The number of ways to order 10 books on a shelf is more than 3.6 million." },
    { word: "Venn diagram", difficulty: "hard", factoid: "John Venn introduced his overlapping circle diagrams in 1880 to teach set logic." },
    { word: "Fibonacci spiral", difficulty: "hard", factoid: "The Fibonacci spiral shows up in sunflower seeds, pinecones, and the swirl of hurricanes." },
  ],

  history: [
    { word: "pyramid", difficulty: "easy", factoid: "The Great Pyramid of Giza held the title of tallest human structure for over 3,800 years." },
    { word: "knight", difficulty: "easy", factoid: "A full set of medieval plate armor weighed about 25 kilograms, lighter than a modern soldier's gear." },
    { word: "castle", difficulty: "easy", factoid: "Some medieval castles had toilets called garderobes that emptied directly into the moat." },
    { word: "sword", difficulty: "easy", factoid: "A Roman gladius sword was short for a reason, it was made for stabbing in tight formation, not slashing." },
    { word: "crown", difficulty: "easy", factoid: "The British crown jewels are valued at billions, but the actual crowns are usually under 2 kilograms." },
    { word: "throne", difficulty: "easy", factoid: "Ancient Egyptian thrones were often made of cedar wood, since cedar didn't grow in Egypt and showed off royal trade power." },
    { word: "Viking ship", difficulty: "easy", factoid: "Viking longships could cross the Atlantic, and one reached North America 500 years before Columbus." },
    { word: "cannon", difficulty: "easy", factoid: "Early cannons were so unreliable they were sometimes more dangerous to the gunner than the enemy." },
    { word: "musket", difficulty: "easy", factoid: "A trained musketeer could fire three shots a minute, modern soldiers fire that in about a second." },
    { word: "torch", difficulty: "easy", factoid: "Olympic torches first appeared in ancient Greece around 776 BCE to honor the goddess Hera." },
    { word: "scroll", difficulty: "easy", factoid: "The Dead Sea Scrolls, found in 1947, included texts over 2,000 years old still readable today." },
    { word: "mummy", difficulty: "easy", factoid: "Ancient Egyptian embalmers removed the brain through the nose using a long bronze hook." },
    { word: "Trojan Horse", difficulty: "easy", factoid: "The Trojan Horse story comes from Virgil's Aeneid, not Homer's Iliad." },
    { word: "Eiffel Tower", difficulty: "easy", factoid: "The Eiffel Tower was originally meant to be a temporary exhibit and almost got demolished in 1909." },
    { word: "Colosseum", difficulty: "easy", factoid: "The Roman Colosseum could be flooded for mock naval battles called naumachia." },
    { word: "Statue of Liberty", difficulty: "easy", factoid: "The Statue of Liberty's copper skin turned green from a century of oxidation; she started out a shiny penny color." },
    { word: "Berlin Wall", difficulty: "easy", factoid: "The Berlin Wall was built in a single night on August 13, 1961, and stood for 28 years." },
    { word: "Boston Tea Party", difficulty: "medium", factoid: "Colonists at the Boston Tea Party dumped 342 chests of British tea worth about 1.7 million dollars today." },
    { word: "Magna Carta", difficulty: "medium", factoid: "Of the 63 clauses in the original 1215 Magna Carta, only 3 are still part of English law today." },
    { word: "Sphinx", difficulty: "medium", factoid: "The Great Sphinx of Giza is carved out of a single massive piece of limestone bedrock." },
    { word: "Roman aqueduct", difficulty: "medium", factoid: "Roman aqueducts had a gradient of about 1 in 4,000, engineering precision that's still admired." },
    { word: "guillotine", difficulty: "medium", factoid: "The guillotine was last used in France in 1977, far more recently than most people guess." },
    { word: "Mona Lisa", difficulty: "medium", factoid: "The Mona Lisa wasn't world-famous until it was stolen from the Louvre in 1911." },
    { word: "Great Wall", difficulty: "medium", factoid: "Despite the myth, you cannot actually see the Great Wall of China from space without strong magnification." },
    { word: "Stonehenge", difficulty: "medium", factoid: "Some Stonehenge bluestones were hauled 240 kilometers from Wales around 2500 BCE." },
    { word: "Parthenon", difficulty: "medium", factoid: "The Parthenon's columns curve outward slightly to look perfectly straight from a distance, Greek optical genius." },
    { word: "Big Ben", difficulty: "medium", factoid: "Big Ben is technically the bell, not the tower or the clock face." },
    { word: "Acropolis", difficulty: "medium", factoid: "The Acropolis means 'high city' in Greek and served as a defensive citadel before its temples." },
    { word: "Tower of Pisa", difficulty: "medium", factoid: "The Tower of Pisa started leaning during construction in 1178 because the soil on one side was too soft." },
    { word: "Wright Flyer", difficulty: "medium", factoid: "The Wright brothers' first powered flight in 1903 lasted only 12 seconds and traveled 36 meters." },
    { word: "Liberty Bell", difficulty: "medium", factoid: "The Liberty Bell cracked the first time it was rung after arriving in Philadelphia in 1752." },
    { word: "Sphinx of Naxos", difficulty: "medium", factoid: "The Sphinx of Naxos sat atop a 12-meter Ionic column at Delphi around 560 BCE." },
    { word: "covered wagon", difficulty: "medium", factoid: "Covered wagons on the Oregon Trail averaged only about 24 kilometers a day." },
    { word: "Spanish galleon", difficulty: "medium", factoid: "Spanish galleons hauled so much New World silver that European inflation spiked for a century." },
    { word: "Apollo 11", difficulty: "medium", factoid: "Apollo 11's onboard computer had less processing power than a modern pocket calculator." },
    { word: "Titanic", difficulty: "medium", factoid: "The Titanic carried only 20 lifeboats, enough for about half the people on board." },
    { word: "Hindenburg", difficulty: "medium", factoid: "The Hindenburg disaster in 1937 took only 32 seconds from first flame to total wreck." },
    { word: "Sputnik", difficulty: "medium", factoid: "Sputnik, the first artificial satellite, was only about the size of a beach ball." },
    { word: "samurai", difficulty: "medium", factoid: "Samurai didn't fight only with swords, they were also expert archers, and the bow came first." },
    { word: "Pony Express", difficulty: "medium", factoid: "The Pony Express only operated for 18 months in 1860 to 1861 before the telegraph made it obsolete." },
    { word: "Rosetta Stone", difficulty: "hard", factoid: "The Rosetta Stone cracked Egyptian hieroglyphs because it carried the same decree in three scripts." },
    { word: "trireme", difficulty: "hard", factoid: "Greek triremes had three rows of rowers stacked vertically and could ram enemy ships at 9 knots." },
    { word: "chariot", difficulty: "hard", factoid: "Roman chariot racing was so popular that star drivers earned more than modern sports superstars do today." },
    { word: "ziggurat", difficulty: "hard", factoid: "Ziggurats were temple-pyramids in ancient Mesopotamia, predating the Egyptian pyramids by centuries." },
    { word: "Stone of Scone", difficulty: "hard", factoid: "British monarchs have been crowned over the Stone of Scone for more than 700 years." },
    { word: "Bayeux Tapestry", difficulty: "hard", factoid: "The Bayeux Tapestry is actually embroidery, not a tapestry, and stretches nearly 70 meters long." },
    { word: "Lascaux cave art", difficulty: "hard", factoid: "The Lascaux cave paintings in France are about 17,000 years old, made by Ice Age artists." },
    { word: "Terracotta Army", difficulty: "hard", factoid: "China's Terracotta Army has over 8,000 soldiers, each with a unique face." },
    { word: "Hanging Gardens", difficulty: "hard", factoid: "The Hanging Gardens of Babylon are the only Wonder of the Ancient World whose existence is still debated." },
    { word: "Aztec calendar", difficulty: "hard", factoid: "The Aztec Sun Stone is over 3 meters across and weighs about 24 tons." },
  ],

  geography: [
    { word: "mountain", difficulty: "easy", factoid: "Mount Everest grows about 4 millimeters taller every year because of tectonic plates colliding." },
    { word: "volcano", difficulty: "easy", factoid: "There are around 1,500 active volcanoes on Earth, plus thousands more under the ocean." },
    { word: "river", difficulty: "easy", factoid: "The Nile and the Amazon both claim the title of longest river, the answer changes by a few kilometers depending on the survey." },
    { word: "lake", difficulty: "easy", factoid: "Lake Baikal in Russia holds about 20 percent of all the unfrozen freshwater on Earth." },
    { word: "ocean", difficulty: "easy", factoid: "We've mapped Mars in more detail than the floor of our own oceans." },
    { word: "island", difficulty: "easy", factoid: "Greenland is the world's largest island; Australia is too big and gets called a continent." },
    { word: "desert", difficulty: "easy", factoid: "Antarctica technically counts as the largest desert on Earth because it gets so little precipitation." },
    { word: "forest", difficulty: "easy", factoid: "The Amazon rainforest produces about 6 percent of the world's oxygen." },
    { word: "beach", difficulty: "easy", factoid: "Most beach sand is made of weathered quartz; some beaches have green, pink, or even black sand from local rocks." },
    { word: "waterfall", difficulty: "easy", factoid: "Angel Falls in Venezuela is so tall the water turns to mist before reaching the bottom." },
    { word: "canyon", difficulty: "easy", factoid: "The Grand Canyon took the Colorado River about 6 million years to carve out." },
    { word: "cave", difficulty: "easy", factoid: "Vietnam's Son Doong cave is so big it has its own clouds and weather system inside." },
    { word: "iceberg", difficulty: "easy", factoid: "Only about 10 percent of an iceberg shows above water, the rest is hidden below." },
    { word: "glacier", difficulty: "easy", factoid: "Glacial ice can be hundreds of thousands of years old, with air bubbles trapped from prehistoric atmospheres." },
    { word: "globe", difficulty: "easy", factoid: "The oldest surviving globe, the Erdapfel from 1492, was made just before Columbus's voyage and shows no Americas." },
    { word: "compass", difficulty: "easy", factoid: "Magnetic north is not the same as true north and slowly drifts, currently about 50 kilometers per year." },
    { word: "map", difficulty: "easy", factoid: "The Mercator map projection makes Greenland look the same size as Africa, even though Africa is 14 times bigger." },
    { word: "lighthouse", difficulty: "easy", factoid: "The Pharos of Alexandria, one of the world's earliest lighthouses, stood over 100 meters tall." },
    { word: "peninsula", difficulty: "medium", factoid: "A peninsula is nearly surrounded by water, Florida and Italy are classic examples." },
    { word: "fjord", difficulty: "medium", factoid: "Fjords were carved by glaciers and can plunge over 1,000 meters deep, deeper than most lakes." },
    { word: "tundra", difficulty: "medium", factoid: "Tundra soil stays frozen year-round, a layer called permafrost." },
    { word: "savanna", difficulty: "medium", factoid: "The African savanna supports the largest land animal migrations on Earth." },
    { word: "delta", difficulty: "medium", factoid: "River deltas are named after the Greek letter delta, which looks like a triangle." },
    { word: "geyser", difficulty: "medium", factoid: "Yellowstone's Old Faithful erupts about every 90 minutes, plus or minus 10." },
    { word: "tornado", difficulty: "medium", factoid: "The strongest tornadoes can pack winds over 480 kilometers per hour." },
    { word: "hurricane", difficulty: "medium", factoid: "A single hurricane can release as much energy in a day as the entire US uses in a year." },
    { word: "monsoon", difficulty: "medium", factoid: "South Asia's monsoon rains can dump over 10 meters of rainfall on some mountainsides in a single season." },
    { word: "coral reef", difficulty: "medium", factoid: "The Great Barrier Reef is so large it can be seen from low Earth orbit." },
    { word: "atoll", difficulty: "medium", factoid: "Atolls are ring-shaped reefs that form when an underwater volcano sinks beneath its own coral cap." },
    { word: "plateau", difficulty: "medium", factoid: "The Tibetan Plateau is so high it's nicknamed the Roof of the World." },
    { word: "isthmus", difficulty: "medium", factoid: "The Isthmus of Panama is the thin strip of land that joins North and South America." },
    { word: "strait", difficulty: "medium", factoid: "The Strait of Gibraltar is only about 13 kilometers wide at its narrowest point." },
    { word: "tributary", difficulty: "medium", factoid: "The Mississippi River has hundreds of tributaries feeding it across 31 US states." },
    { word: "equator", difficulty: "medium", factoid: "If you stood exactly on the equator, you'd be moving about 1,670 kilometers per hour just from Earth's spin." },
    { word: "tropics", difficulty: "medium", factoid: "The tropics get more direct sunlight year-round, which is why they tend to be warmer and wetter." },
    { word: "tectonic plate", difficulty: "medium", factoid: "The Pacific Plate moves about as fast as your fingernails grow." },
    { word: "continent", difficulty: "medium", factoid: "All seven continents were once joined as a supercontinent called Pangaea, around 300 million years ago." },
    { word: "archipelago", difficulty: "hard", factoid: "Indonesia is the largest archipelago, made up of over 17,000 islands." },
    { word: "estuary", difficulty: "hard", factoid: "Estuaries are where rivers meet the sea, mixing fresh and salt water and packing more marine life per square meter than almost any other habitat." },
    { word: "moraine", difficulty: "hard", factoid: "Moraines are piles of rock and dirt left behind when glaciers melt and retreat." },
    { word: "caldera", difficulty: "hard", factoid: "A caldera forms when a volcano collapses inward after a huge eruption, Yellowstone sits on one." },
    { word: "permafrost", difficulty: "hard", factoid: "Some Siberian permafrost has frozen mammoth corpses still intact after 30,000 years." },
    { word: "stalactite", difficulty: "hard", factoid: "Stalactites hang from a cave ceiling; stalagmites grow up from the floor, easy mnemonic: c for ceiling, g for ground." },
    { word: "meander", difficulty: "hard", factoid: "Meanders are the snake-like bends in a river that slowly migrate over thousands of years." },
    { word: "oxbow lake", difficulty: "hard", factoid: "An oxbow lake forms when a river meander gets pinched off and abandoned by the main flow." },
    { word: "Mariana Trench", difficulty: "hard", factoid: "The Mariana Trench is 11 kilometers deep, deeper than Mount Everest is tall." },
    { word: "Sahara Desert", difficulty: "hard", factoid: "The Sahara was lush and green just 6,000 years ago, with rivers, lakes, and hippos." },
    { word: "Bermuda Triangle", difficulty: "hard", factoid: "Statistically, the Bermuda Triangle doesn't lose more ships than any other busy stretch of ocean." },
    { word: "Dead Sea", difficulty: "hard", factoid: "The Dead Sea is so salty you basically float without trying, about 10 times saltier than the ocean." },
    { word: "Mount Fuji", difficulty: "hard", factoid: "Mount Fuji is technically three volcanoes stacked on top of each other." },
  ],

  astronomy: [
    { word: "sun", difficulty: "easy", factoid: "The sun accounts for about 99.86 percent of all mass in our solar system." },
    { word: "moon", difficulty: "easy", factoid: "The moon is slowly drifting away from Earth at about 3.8 centimeters per year." },
    { word: "Earth", difficulty: "easy", factoid: "Earth is the only known planet where water exists naturally as a solid, liquid, and gas at the same time." },
    { word: "Mars", difficulty: "easy", factoid: "Mars has the tallest volcano in the solar system, Olympus Mons, almost three times Everest's height." },
    { word: "Jupiter", difficulty: "easy", factoid: "Jupiter is so massive it could fit over 1,300 Earths inside it." },
    { word: "Saturn", difficulty: "easy", factoid: "Saturn is so low density it would float in water if you had a bathtub big enough." },
    { word: "Venus", difficulty: "easy", factoid: "A day on Venus is longer than a year on Venus, thanks to its slow backwards spin." },
    { word: "Mercury", difficulty: "easy", factoid: "Mercury's temperature swings over 600 degrees Celsius between day and night sides." },
    { word: "Neptune", difficulty: "easy", factoid: "Neptune has the fastest winds in the solar system, over 2,000 kilometers per hour." },
    { word: "Uranus", difficulty: "easy", factoid: "Uranus spins on its side, probably from a giant collision in its ancient past." },
    { word: "star", difficulty: "easy", factoid: "Every star you see at night is bigger than Earth, no exceptions." },
    { word: "comet", difficulty: "easy", factoid: "Comet tails always point away from the sun, no matter which direction the comet is flying." },
    { word: "asteroid", difficulty: "easy", factoid: "If you smashed every asteroid in the main belt together, you'd still get less mass than our moon." },
    { word: "rocket", difficulty: "easy", factoid: "The Saturn V rocket that sent astronauts to the moon used 200,000 gallons of fuel per minute at launch." },
    { word: "satellite", difficulty: "easy", factoid: "There are over 9,000 active satellites orbiting Earth right now." },
    { word: "telescope", difficulty: "easy", factoid: "The James Webb Space Telescope can see infrared light from galaxies that formed just 200 million years after the Big Bang." },
    { word: "astronaut", difficulty: "easy", factoid: "Astronauts can grow up to 5 centimeters taller in space because their spines stretch without gravity." },
    { word: "alien", difficulty: "easy", factoid: "We've never confirmed alien life, but extremophiles on Earth survive in places we used to call impossible." },
    { word: "galaxy", difficulty: "medium", factoid: "The Milky Way galaxy is on a collision course with Andromeda, set to merge in about 4.5 billion years." },
    { word: "constellation", difficulty: "medium", factoid: "Stars in a constellation are usually nowhere near each other; they only line up from our viewpoint." },
    { word: "nebula", difficulty: "medium", factoid: "Most nebulae are nurseries where new stars are being born from collapsing gas clouds." },
    { word: "black hole", difficulty: "medium", factoid: "If you fell into a black hole, time would appear to freeze from an outside observer's perspective." },
    { word: "supernova", difficulty: "medium", factoid: "A supernova can briefly outshine its entire host galaxy." },
    { word: "meteor", difficulty: "medium", factoid: "About 100 tons of space dust and debris falls onto Earth every day." },
    { word: "meteorite", difficulty: "medium", factoid: "Most meteorites that hit Earth are over 4.5 billion years old, predating our planet." },
    { word: "orbit", difficulty: "medium", factoid: "The International Space Station orbits Earth at about 28,000 kilometers per hour." },
    { word: "eclipse", difficulty: "medium", factoid: "Total solar eclipses happen because the sun is roughly 400 times bigger than the moon and 400 times farther away." },
    { word: "sunspot", difficulty: "medium", factoid: "Sunspots look dark only because they're cooler than the surrounding solar surface, they're still over 3,000 degrees Celsius." },
    { word: "solar flare", difficulty: "medium", factoid: "A strong solar flare can knock out power grids on Earth, like the 1989 Quebec blackout." },
    { word: "aurora", difficulty: "medium", factoid: "Auroras happen when charged particles from the sun crash into Earth's magnetic field." },
    { word: "Milky Way", difficulty: "medium", factoid: "Our solar system orbits the center of the Milky Way once every 225 million years." },
    { word: "space station", difficulty: "medium", factoid: "The International Space Station has been continuously occupied by humans since November 2000." },
    { word: "rover", difficulty: "medium", factoid: "NASA's Opportunity rover was meant to last 90 days on Mars; it survived nearly 15 years." },
    { word: "space suit", difficulty: "medium", factoid: "A modern NASA spacesuit weighs about 130 kilograms on Earth but feels weightless in orbit." },
    { word: "lunar lander", difficulty: "medium", factoid: "The Apollo lunar lander had walls thinner than a soda can to save weight." },
    { word: "Halley's Comet", difficulty: "medium", factoid: "Halley's Comet returns near Earth every 76 years; next pass is 2061." },
    { word: "solar system", difficulty: "medium", factoid: "If the sun were the size of a basketball, Earth would be a peppercorn 30 meters away." },
    { word: "asteroid belt", difficulty: "medium", factoid: "The asteroid belt sits between Mars and Jupiter and isn't crowded like the movies, you could fly through without dodging." },
    { word: "pulsar", difficulty: "hard", factoid: "Pulsars are dead stars that spin hundreds of times per second, beaming radio waves like cosmic lighthouses." },
    { word: "quasar", difficulty: "hard", factoid: "Quasars are powered by supermassive black holes and can outshine entire galaxies." },
    { word: "redshift", difficulty: "hard", factoid: "Redshift lets us measure how fast a galaxy is moving away by how stretched its light becomes." },
    { word: "exoplanet", difficulty: "hard", factoid: "We've confirmed over 5,000 exoplanets orbiting other stars, and some look earthlike." },
    { word: "wormhole", difficulty: "hard", factoid: "Wormholes are theoretical tunnels through spacetime predicted by general relativity but never observed." },
    { word: "white dwarf", difficulty: "hard", factoid: "A teaspoon of white dwarf material would weigh several tons on Earth." },
    { word: "neutron star", difficulty: "hard", factoid: "A sugar cube of neutron star material would weigh roughly a billion tons." },
    { word: "Kuiper Belt", difficulty: "hard", factoid: "The Kuiper Belt is a ring of icy bodies beyond Neptune, including Pluto." },
    { word: "Oort Cloud", difficulty: "hard", factoid: "The Oort Cloud may extend nearly halfway to the next star, and is where most long-period comets come from." },
    { word: "binary star", difficulty: "hard", factoid: "More than half the stars in our galaxy are part of binary or multiple-star systems." },
    { word: "dark matter", difficulty: "hard", factoid: "Dark matter makes up about 27 percent of the universe but no one has ever seen it directly." },
    { word: "gravitational wave", difficulty: "hard", factoid: "Gravitational waves from colliding black holes were first directly detected in 2015." },
  ],

  "pop-culture": [
    { word: "pizza", difficulty: "easy", factoid: "The first pizza delivery on record was made in 1889 to the Queen of Italy, who loved the Margherita." },
    { word: "taco", difficulty: "easy", factoid: "The word taco originally referred to small charges of dynamite used in Mexican silver mines." },
    { word: "burger", difficulty: "easy", factoid: "Americans eat about 50 billion burgers every year, about 3 per person, per week." },
    { word: "sneaker", difficulty: "easy", factoid: "Sneakers got their name in the 1800s because rubber soles made them quiet enough to sneak around in." },
    { word: "skateboard", difficulty: "easy", factoid: "Skateboards started as surfboards with roller-skate wheels nailed to the bottom in 1950s California." },
    { word: "basketball", difficulty: "easy", factoid: "Basketball was invented in 1891 by James Naismith with a peach basket and a soccer ball." },
    { word: "soccer ball", difficulty: "easy", factoid: "The classic black-and-white soccer ball pattern was designed in 1962 to show up clearly on black-and-white TV." },
    { word: "guitar", difficulty: "easy", factoid: "The Fender Stratocaster, released in 1954, is one of the most copied electric guitar designs ever." },
    { word: "headphones", difficulty: "easy", factoid: "The first commercial headphones were made in 1910 by a Utah inventor working at his kitchen table." },
    { word: "camera", difficulty: "easy", factoid: "The first photograph ever taken, in 1826, required an exposure time of about 8 hours." },
    { word: "selfie", difficulty: "easy", factoid: "The word selfie was named Oxford Dictionary's word of the year in 2013." },
    { word: "emoji", difficulty: "easy", factoid: "The first emoji set was created in 1999 in Japan by Shigetaka Kurita on a 12-by-12 pixel grid." },
    { word: "controller", difficulty: "easy", factoid: "The classic D-pad on game controllers was patented by Nintendo's Gunpei Yokoi in 1982." },
    { word: "TikTok", difficulty: "easy", factoid: "TikTok was originally called Musical.ly before being acquired and rebranded in 2018." },
    { word: "YouTube", difficulty: "easy", factoid: "The very first YouTube video was uploaded April 23, 2005 and was just 19 seconds at the San Diego Zoo." },
    { word: "Pokemon", difficulty: "easy", factoid: "Pokemon was inspired by creator Satoshi Tajiri's childhood hobby of collecting bugs." },
    { word: "Mario", difficulty: "easy", factoid: "Mario originally had no name and was just called Jumpman in the 1981 Donkey Kong arcade game." },
    { word: "Spider-Man", difficulty: "easy", factoid: "Spider-Man was almost rejected by Marvel in 1962 because the publisher hated spiders." },
    { word: "Batman", difficulty: "easy", factoid: "Batman's original 1939 design had red tights and no cape, the bat cape came later that year." },
    { word: "Star Wars", difficulty: "easy", factoid: "George Lucas was so unsure Star Wars would succeed that he traded his director's salary for merchandising rights." },
    { word: "Harry Potter", difficulty: "easy", factoid: "Twelve publishers rejected the first Harry Potter book before Bloomsbury said yes." },
    { word: "Mickey Mouse", difficulty: "easy", factoid: "Mickey Mouse was originally going to be named Mortimer until Walt Disney's wife suggested Mickey." },
    { word: "SpongeBob", difficulty: "easy", factoid: "SpongeBob's creator Stephen Hillenburg was a marine biologist before making cartoons." },
    { word: "DJ turntable", difficulty: "easy", factoid: "Scratching as a DJ technique was popularized by Grand Wizzard Theodore in the Bronx in 1975." },
    { word: "popcorn", difficulty: "easy", factoid: "Movie theaters didn't sell popcorn until the Great Depression made cheap snacks essential to staying open." },
    { word: "donut", difficulty: "easy", factoid: "The hole in donuts was reportedly invented by a sea captain in 1847 to make them cook through evenly." },
    { word: "sushi", difficulty: "easy", factoid: "Sushi originally started as a way to preserve fish in fermented rice, the rice was thrown away." },
    { word: "ice cream", difficulty: "easy", factoid: "The waffle cone was invented at the 1904 St. Louis World's Fair when an ice cream vendor ran out of bowls." },
    { word: "Spotify", difficulty: "easy", factoid: "Spotify launched in 2008 in Sweden and now has over 600 million users worldwide." },
    { word: "Netflix", difficulty: "easy", factoid: "Netflix started in 1997 as a DVD-by-mail company before pivoting to streaming." },
    { word: "smartphone", difficulty: "medium", factoid: "The first iPhone, released in 2007, had less storage than a single song takes up today in lossless audio." },
    { word: "laptop", difficulty: "medium", factoid: "The first laptop, the Osborne 1 from 1981, weighed about 11 kilograms and had a 5-inch screen." },
    { word: "gaming console", difficulty: "medium", factoid: "The Magnavox Odyssey, released in 1972, was the first home gaming console, it predated the Atari." },
    { word: "vinyl record", difficulty: "medium", factoid: "Vinyl record sales have grown every year since 2006, even with streaming dominating." },
    { word: "cassette tape", difficulty: "medium", factoid: "The cassette tape was invented in 1963 by Philips and was the first portable format for music." },
    { word: "boombox", difficulty: "medium", factoid: "The boombox got its nickname in the late 1970s because nothing else could pump that much volume on the street." },
    { word: "Walkman", difficulty: "medium", factoid: "The Sony Walkman, released in 1979, sold over 200 million units before iPods took over." },
    { word: "Game Boy", difficulty: "medium", factoid: "The original Game Boy from 1989 ran for over 30 hours on four AA batteries." },
    { word: "Rubik's Cube", difficulty: "medium", factoid: "There are over 43 quintillion ways to scramble a Rubik's Cube, but any one can be solved in 20 moves or fewer." },
    { word: "Tamagotchi", difficulty: "medium", factoid: "Tamagotchis sold over 80 million units since 1996, many schools banned them for distracting students." },
    { word: "yo-yo", difficulty: "medium", factoid: "The yo-yo dates back over 2,500 years to ancient Greece and China." },
    { word: "lava lamp", difficulty: "medium", factoid: "Lava lamps were invented in 1963 by a British accountant who saw a homemade egg timer in a pub." },
    { word: "vending machine", difficulty: "medium", factoid: "The first vending machine, in ancient Egypt, dispensed holy water for a coin." },
    { word: "ATM", difficulty: "medium", factoid: "The first ATM was installed in London in 1967 and used radioactive cheques to verify users." },
    { word: "shopping cart", difficulty: "medium", factoid: "The shopping cart was invented in 1937, and shoppers initially hated using them because they felt childish." },
    { word: "umbrella", difficulty: "medium", factoid: "Umbrellas were used in ancient China over 4,000 years ago and were originally a status symbol, not for rain." },
    { word: "stop sign", difficulty: "medium", factoid: "The first stop sign appeared in Detroit in 1915 and was originally yellow with black letters." },
    { word: "traffic light", difficulty: "medium", factoid: "The first electric traffic light was installed in Cleveland in 1914." },
    { word: "Lego", difficulty: "medium", factoid: "There are about 80 Lego bricks for every person on Earth." },
    { word: "Slinky", difficulty: "medium", factoid: "The Slinky was invented in 1943 by a naval engineer who accidentally knocked a spring off his desk." },
  ],
};
