// Hand-authored pool extras that show off the chain mechanics, plus a second
// incident template for the Doubles modifier. Kept here (not in the generated
// JSON) because chains and incident groups are structural, not flat tickets.

import type { ShiftItem } from "./types";
import type { Track } from "@/lib/helpdesk/types";

export const EXTRA_TICKETS: { item: ShiftItem; track: Track }[] = [
  {
    track: "helpdesk",
    item: {
      id: "onboard-laptop",
      channel: "ticket",
      priority: "P3",
      from: { name: "HR Onboarding", role: "People Ops" },
      subject: "Provision a new hire's laptop for Monday",
      slaMinutes: 60,
      arriveAfter: 0,
      reward: 40,
      xp: 32,
      ticketBody: "New hire starts Monday. Their laptop needs to be imaged and enrolled before then.",
      goal: "Get the new hire's laptop ready.",
      hint: "Onboarding is a sequence. Image and enroll the device the standard way.",
      actions: [
        { id: "image-enroll", label: "Image the laptop and enroll it in MDM", correct: true, csat: 11, teach: "Standard onboarding. The device is ready. A laptop is only half of it though." },
        { id: "hand-blank", label: "Hand them the laptop as-is", csat: -5, teach: "An un-imaged, unenrolled laptop has no apps, no policies, no security baseline. Image and enroll it first." },
        { id: "local-admin", label: "Give them local admin and let them set it up", csat: -6, teach: "Handing a new hire local admin on an unmanaged box is a security and support nightmare. Provision it properly." },
      ],
      chainOnResolve: {
        id: "onboard-mailbox",
        channel: "ticket",
        priority: "P3",
        from: { name: "Sasha (new hire)", role: "Sales" },
        subject: "I can log in but I have no email",
        slaMinutes: 45,
        arriveAfter: 0,
        reward: 34,
        xp: 26,
        ticketBody: "The laptop works but Outlook says there's no account. I can't see any email.",
        goal: "Finish the onboarding: get their mailbox working.",
        hint: "The device is done; the identity side isn't. What did onboarding still owe them?",
        actions: [
          { id: "provision-mailbox", label: "Provision their mailbox and assign the license", correct: true, csat: 11, teach: "That's the other half of onboarding: device plus identity. Now they're fully set up." },
          { id: "reinstall-outlook", label: "Reinstall Outlook", csat: -4, teach: "Outlook is fine; there's no mailbox to connect to yet. Provision the account, not the app." },
          { id: "wait-sync", label: "Tell them it'll sync eventually", csat: -5, teach: "It won't sync a mailbox that was never created. Provision it." },
        ],
      },
    },
  },
  {
    track: "helpdesk",
    item: {
      id: "slow-pc-callback",
      channel: "ticket",
      priority: "P3",
      from: { name: "Ben Carter", role: "Finance" },
      subject: "My PC has been really slow all morning",
      slaMinutes: 45,
      arriveAfter: 0,
      reward: 38,
      xp: 30,
      ticketBody: "Everything is sluggish today, opening anything takes forever. Can you take a look?",
      evidence: [{ label: "Task Manager (shared)", lines: ["process 'idx_helper.exe' pinned at 95% CPU", "started 08:02, never settled", "everything else starved for CPU"] }],
      goal: "Actually fix Ben's slow PC.",
      hint: "There's a real cause in the task list. Don't fob him off with a generic restart.",
      actions: [
        { id: "kill-indexer", label: "End the runaway indexer process and stop it auto-starting", correct: true, csat: 12, teach: "Right. A stuck indexer was eating the CPU. Killing it and stopping the auto-start fixes the actual problem." },
        { id: "add-ram-slow", label: "Order him more RAM", csat: -5, teach: "It's a pegged CPU from one process, not memory pressure. More RAM won't touch it." },
        { id: "fob-off", label: "Tell him to just restart and close the ticket", csat: -8, ends: true, outcome: "mishandled", teach: "You closed it without finding the cause. A restart clears it for a minute, but the auto-starting indexer pegs the CPU again. Fobbing users off is how tickets come back angrier." },
      ],
      chainOnFail: {
        id: "slow-pc-angry",
        channel: "ticket",
        priority: "P1",
        from: { name: "Ben Carter", role: "Finance", vip: true },
        subject: "It is STILL slow and I've lost an hour",
        slaMinutes: 15,
        arriveAfter: 0,
        reward: 30,
        xp: 24,
        ticketBody: "I restarted like you said and it's slow AGAIN. I've wasted my whole morning. Fix it properly this time.",
        evidence: [{ label: "Task Manager", lines: ["'idx_helper.exe' back at 95% CPU after the reboot", "it auto-starts at login"] }],
        goal: "Make it right, and find the real cause this time.",
        hint: "It came back because the cause was never addressed. The process auto-starts.",
        actions: [
          { id: "kill-indexer-2", label: "End the indexer and disable its auto-start", correct: true, csat: 10, teach: "Fixed at the source this time. The lesson stings but sticks: solve the cause the first time, or it comes back worse." },
          { id: "reimage-angry", label: "Reimage his machine to be safe", csat: -6, teach: "A full reimage over one runaway process is overkill and more downtime for an already-furious user. Kill the process." },
        ],
      },
    },
  },
  {
    track: "helpdesk",
    item: {
      id: "printer-then-scanner",
      channel: "ticket",
      priority: "P3",
      from: { name: "Reception", role: "Front Desk" },
      subject: "The lobby printer is offline",
      slaMinutes: 40,
      arriveAfter: 0,
      reward: 38,
      xp: 30,
      ticketBody: "The big lobby MFP shows offline and won't print.",
      evidence: [{ label: "MFP status", lines: ["MFP-LOBBY: offline", "network cable unplugged at the wall", "toner and paper fine"] }],
      goal: "Get the lobby printer back.",
      hint: "It says offline and the basics are fine. Check the physical link before anything fancy.",
      actions: [
        { id: "reconnect-mfp", label: "Reconnect the network cable and bring it back online", correct: true, csat: 11, teach: "Simple physical fix. It's back online. These multifunction units do more than print, though." },
        { id: "reinstall-mfp-driver", label: "Reinstall the printer driver", csat: -4, teach: "The driver's fine; the cable was unplugged. Check connectivity first, drivers last." },
        { id: "replace-mfp", label: "Order a replacement printer", csat: -6, teach: "A working printer with an unplugged cable doesn't need replacing. Plug it back in." },
      ],
      chainOnResolve: {
        id: "scanner-followup",
        channel: "ticket",
        priority: "P3",
        from: { name: "Reception", role: "Front Desk" },
        subject: "Now scan-to-email isn't working on it",
        slaMinutes: 40,
        arriveAfter: 0,
        reward: 32,
        xp: 26,
        ticketBody: "Printing works again but the scan-to-email button just errors.",
        evidence: [{ label: "MFP scan log", lines: ["scan-to-email: SMTP auth failed", "the saved app password expired last week"] }],
        goal: "Finish the job: get scan-to-email working.",
        hint: "Same device, different function. The error points at email auth, not the network.",
        actions: [
          { id: "renew-smtp", label: "Update the MFP's scan-to-email credentials", correct: true, csat: 11, teach: "Right. The saved SMTP app password expired, so scanning to email failed even though printing was fine. Renew it and it scans again." },
          { id: "reboot-mfp", label: "Reboot the MFP", csat: -4, teach: "A reboot won't refresh an expired credential. Update the scan-to-email auth." },
        ],
      },
    },
  },
  {
    track: "helpdesk",
    item: {
      id: "admin-rights-request",
      channel: "ticket",
      priority: "P3",
      from: { name: "Greg Mills", role: "Marketing" },
      subject: "I need admin rights to install a design tool",
      slaMinutes: 45,
      arriveAfter: 0,
      reward: 38,
      xp: 30,
      ticketBody: "I found a free design app online and need local admin to install it. Can you just give me admin?",
      goal: "Handle the request the right way.",
      hint: "There's a safe way to get users software, and it isn't handing out local admin for a random download.",
      actions: [
        { id: "software-center", label: "Offer it through the vetted software center, or package the app first", correct: true, csat: 12, teach: "Right. Users get software through a vetted channel, not local admin on a random download. If it's legit, package it; if not, suggest an approved alternative." },
        { id: "deny-explain", label: "Decline local admin and explain the policy", csat: -2, teach: "Declining is safe, but leaving the user stuck isn't great. Offer the vetted path so they can still get what they need." },
        { id: "grant-admin", label: "Just grant local admin so he can install it", csat: -8, ends: true, outcome: "mishandled", teach: "Handing local admin for an unvetted internet download is exactly how bad things get installed. This one comes back." },
      ],
      chainOnFail: {
        id: "malware-callback",
        channel: "ticket",
        priority: "P1",
        from: { name: "SOC", role: "Security", vip: true },
        subject: "That 'design app' is flagged as malware on Greg's PC",
        slaMinutes: 15,
        arriveAfter: 0,
        reward: 30,
        xp: 24,
        ticketBody: "The tool you let Greg install with local admin is throwing EDR alerts. It's bundled malware. We need this contained.",
        evidence: [{ label: "EDR", lines: ["unsigned installer dropped two extra processes", "beaconing to an ad network", "local admin let it persist"] }],
        goal: "Clean up the mess and contain it.",
        hint: "You gave it admin and it abused that. Stop it spreading and remove the access.",
        actions: [
          { id: "isolate-remove", label: "Isolate the PC, remove the malware, and revoke the local admin", correct: true, csat: 10, teach: "Contained. The lesson lands: granting local admin for an unvetted download let malware install and persist. Vetted channels exist for exactly this reason." },
          { id: "just-uninstall", label: "Just uninstall the app", csat: -6, teach: "It already dropped extra processes and is beaconing. An uninstall won't catch those. Isolate and remediate, and pull the admin rights." },
        ],
      },
    },
  },

  // ── Phone calls. The followups ARE the diagnostic: ask the right question to
  // pin the issue (which stops the patience drain), then the fix unlocks. The
  // correct fix requires ["phone"], so you cannot resolve a call you never
  // actually listened to.
  {
    track: "helpdesk",
    item: {
      id: "call-vpn-home",
      channel: "phone",
      priority: "P2",
      from: { name: "Diego Salas", role: "Sales" },
      subject: "VPN won't connect from home",
      slaMinutes: 20,
      arriveAfter: 0,
      reward: 42,
      xp: 34,
      phone: {
        opener: "Hey, I'm working from home and the VPN just spins forever and never connects. I've got a deadline, can you help?",
        followups: [
          { label: "Did you get the multi-factor prompt on your phone when it tried to connect?", reply: "Now that you mention it, no, no prompt ever showed up.", correct: true },
          { label: "Have you tried restarting your computer?", reply: "Yeah, twice already. Same thing." },
          { label: "Is your home wifi working otherwise?", reply: "Yes, everything else loads fine." },
        ],
      },
      goal: "Find out why the VPN hangs, then fix it.",
      hint: "A VPN that spins forever often isn't the network. What step has to complete that the user might not be seeing?",
      actions: [
        { id: "reenroll-mfa", label: "Re-enroll their MFA device so the second factor can complete", correct: true, requires: ["phone"], csat: 12, teach: "Right. No MFA prompt means the second factor never fired, so the tunnel never finishes. Re-enrolling their authenticator fixes it. The spinning was the client waiting on a factor that never came." },
        { id: "reset-vpn-config", label: "Reset their VPN client config", requires: ["phone"], csat: -5, teach: "The client is fine; the second factor never prompted. Resetting the config wastes their deadline and doesn't touch the cause." },
        { id: "hotspot", label: "Tell them to switch to a mobile hotspot", csat: -6, teach: "Their home network is fine and you never pinned the issue. Ask the right question before you send them chasing their router." },
      ],
    },
  },
  {
    track: "helpdesk",
    item: {
      id: "call-locked-vip",
      channel: "phone",
      priority: "P1",
      from: { name: "Karen Pruitt", role: "VP Finance", vip: true },
      subject: "Locked out minutes before a board meeting",
      slaMinutes: 15,
      arriveAfter: 0,
      reward: 50,
      xp: 42,
      phone: {
        opener: "This is Karen, I present to the board in ten minutes and I am completely locked out of my laptop. Please hurry.",
        followups: [
          { label: "Did you recently change your password, or is it prompting you for a new one?", reply: "Yes. It forced a change on Friday and I think I forgot the new one.", correct: true },
          { label: "Is caps lock maybe on?", reply: "No, I already checked that." },
          { label: "Is your wifi connected?", reply: "I cannot even log in, so I have no idea." },
        ],
      },
      goal: "Get her back in, the right way, under pressure.",
      hint: "She is important and she is rushing you. That is exactly when the verification step matters most.",
      actions: [
        { id: "verify-then-reset", label: "Verify her identity, then trigger a secure password reset and walk her through a new one", correct: true, requires: ["phone"], csat: 14, teach: "Correct, even under pressure. A forgotten post-change password is a reset, but you verify identity first. Doing it calmly gets the VP back in and keeps the door shut to anyone impersonating her." },
        { id: "reset-no-verify", label: "Just reset it immediately without verifying, she's clearly the VP", csat: -8, ends: true, outcome: "mishandled", teach: "A panicked caller claiming to be an executive is the classic social-engineering setup. Resetting credentials without verifying identity is how attackers walk in. Verify first, every time, no matter who they say they are." },
        { id: "tell-her-wait", label: "Tell her to file a ticket and wait in the queue", requires: ["phone"], csat: -6, teach: "You pinned the issue and then stranded her before the board. A verified reset takes a minute. Make the right call quickly." },
      ],
    },
  },
  {
    track: "helpdesk",
    item: {
      id: "call-dead-laptop",
      channel: "phone",
      priority: "P3",
      from: { name: "Priya Anand", role: "Design" },
      subject: "Laptop is totally dead, demo this afternoon",
      slaMinutes: 30,
      arriveAfter: 0,
      reward: 38,
      xp: 30,
      phone: {
        opener: "My laptop is completely dead, no lights, nothing at all. I have to give a demo this afternoon and I'm panicking.",
        followups: [
          { label: "Is the charger plugged in, and do you see any light on the charger or laptop?", reply: "Huh, the charger light is off. The cable looks loose where it meets the wall.", correct: true },
          { label: "Have you tried holding the power button down?", reply: "Yes, held it for ten seconds, nothing." },
          { label: "Is the screen brightness turned all the way up?", reply: "It's totally black, there's no backlight at all." },
        ],
      },
      goal: "Figure out why it's dead before you escalate to hardware.",
      hint: "Dead means no power. Before you send a tech or order hardware, confirm power is actually reaching it.",
      actions: [
        { id: "reseat-charger", label: "Have them reseat the charger at the wall and the laptop, then confirm it charges", correct: true, requires: ["phone"], csat: 11, teach: "That's it. A loose charger at the wall meant zero power, which looks identical to a dead machine. Reseating it lights the charger and it boots. Cheapest fix there is, and you asked the question that found it." },
        { id: "order-replacement", label: "Order them a replacement laptop", requires: ["phone"], csat: -6, teach: "You confirmed the charger light was off. That's a power-delivery issue, not a dead laptop. Don't burn budget on hardware you don't need." },
        { id: "book-repair", label: "Book a hardware repair appointment", csat: -5, teach: "Booking a repair before checking power sends a working laptop to the bench. Ask about power first." },
      ],
    },
  },
  {
    track: "helpdesk",
    item: {
      id: "call-phish-report",
      channel: "phone",
      priority: "P2",
      from: { name: "Tom Reilly", role: "Operations" },
      subject: "Caller asking if a 'mailbox full' email is real",
      slaMinutes: 25,
      arriveAfter: 0,
      reward: 40,
      xp: 32,
      phone: {
        opener: "I got an email saying my mailbox is full and I have to verify my password at a link or lose my email. It looks official. Is it real? I almost clicked.",
        followups: [
          { label: "Can you read me the sender's address and the link domain exactly?", reply: "Sender is it-support@mail-secure-verify.com and the link goes to mail-secure-verify dot com.", correct: true },
          { label: "Did you click the link?", reply: "No, I called you first." },
          { label: "Can you tell me your password so I can check the account?", reply: "Wait, why would you need my password?" },
        ],
      },
      goal: "Decide what this is and handle it without making it worse.",
      hint: "The pin is in the sender and the link. And note: you never need their password to help them.",
      actions: [
        { id: "confirm-phish-report", label: "Confirm it's phishing, tell them not to click, report it, and check who else received it", correct: true, requires: ["phone"], csat: 12, outcome: "reported", teach: "Right call. A lookalike domain asking for password verification is textbook phishing. Praise them for asking, report it, and pull it from other mailboxes since it likely hit more than one person." },
        { id: "just-delete", label: "Tell them to just delete it and move on", requires: ["phone"], csat: -5, teach: "Deleting protects one person. If it landed in their inbox it landed in others. Report it so it can be pulled org-wide." },
        { id: "reset-their-pw", label: "Reset their password just to be safe", csat: -4, teach: "They told you they didn't click. Resetting is noise, and you skipped the real job: report it and protect everyone else who got the same message." },
      ],
    },
  },
];

// A second incident group (file-server outage) so Doubles has more variety.
export const EXTRA_INCIDENT_GROUPS: { group: string; track: Track; items: ShiftItem[] }[] = [
  {
    group: "fileserver-down",
    track: "helpdesk",
    items: [
      {
        id: "fs-root",
        channel: "ticket",
        priority: "P1",
        from: { name: "Multiple users", role: "Floor 2" },
        subject: "Nobody can open shared files",
        slaMinutes: 15,
        arriveAfter: 0,
        reward: 55,
        xp: 44,
        incident: { group: "fileserver-down", root: true },
        ticketBody: "A wave of tickets: nobody on floor 2 can open anything on the S: drive.",
        evidence: [{ label: "File service", lines: ["fileserver01: 'LanmanServer' service STOPPED (crashed 10:31)", "disk and network healthy", "all share access fails"] }],
        commands: [{ aliases: ["status", "services", "service"], output: "fileserver01: the file-sharing service crashed at 10:31. Disk and network are fine. Restarting the service restores all shares.", step: "diag" }],
        goal: "Restore file access for the floor. Find the single cause.",
        hint: "Every share fails at once and the server's disk and network are fine. What do they all depend on?",
        actions: [
          { id: "restart-fs-service", label: "Restart the file-sharing service", correct: true, requires: ["diag"], csat: 16, teach: "That's the incident. The file service crashed, so every share went dark at once. Restarting it brings them all back and clears the flood of duplicates." },
          { id: "reboot-fs", label: "Reboot the whole file server", csat: -5, teach: "A full reboot works but takes the server offline for minutes when only one service needed restarting." },
          { id: "restore-fs", label: "Start restoring from backup", csat: -7, teach: "Nothing was lost; the service just stopped. Restoring from backup is a huge needless operation. Restart the service." },
        ],
      },
      {
        id: "fs-dup-1",
        channel: "ticket",
        priority: "P2",
        from: { name: "Tara", role: "Accounting" },
        subject: "S: drive won't open",
        slaMinutes: 20,
        arriveAfter: 8,
        reward: 8,
        xp: 6,
        incident: { group: "fileserver-down" },
        ticketBody: "My S: drive gives an error. Is it just me?",
        goal: "Handle it. Familiar?",
        hint: "Others are reporting the same thing right now.",
        actions: [
          { id: "ack-fs-1", label: "Link it to the file-server incident", correct: true, csat: 2, outcome: "resolved", teach: "Right, it's the outage. The root fix closes this." },
          { id: "remap-1", label: "Walk her through remapping the drive", csat: -3, teach: "Her mapping is fine; the server's service is down. It's the incident, not her PC." },
        ],
      },
      {
        id: "fs-dup-2",
        channel: "ticket",
        priority: "P3",
        from: { name: "Owen", role: "Sales" },
        subject: "can't get to the shared folder",
        slaMinutes: 25,
        arriveAfter: 16,
        reward: 8,
        xp: 6,
        incident: { group: "fileserver-down" },
        ticketBody: "Shared folder throws an error for me too.",
        goal: "Same incident.",
        hint: "Fix the root and this closes itself.",
        actions: [
          { id: "ack-fs-2", label: "Link it to the file-server incident", correct: true, csat: 2, outcome: "resolved", teach: "Yep, the root fix mass-resolves these." },
          { id: "reboot-owen", label: "Tell him to reboot his PC", csat: -4, teach: "His PC is fine. It's a server-side outage." },
        ],
      },
    ],
  },
];
