/**
 * Web shim — re-exports from @lionade/core/types/supabase.
 *
 * The canonical source lives in packages/lionade-core/src/types/supabase.ts.
 * Both web and iOS import from there. This shim keeps existing
 * `import { Database } from '@/types/supabase'` imports working.
 *
 * New code should import directly from '@lionade/core/types/supabase'.
 *
 * DO NOT HAND-EDIT. The source file is auto-generated by Supabase CLI.
 */
export * from "@lionade/core/types/supabase";
