// Spectrum Slider — curated estimation prompts.
//
// Each entry has a prompt, the TRUE value, and a [min, max] range that defines
// the slider domain. The player drags a slider (0-100%) mapped linearly onto
// [min, max]; the closer their value is to the true value, the more points they
// score (distance-based partial credit, computed in lib/competitive/scoring of
// the shared platform). Both players answer the same prompt each round.
//
// Values are well-established and verifiable. Where a value is approximate
// (e.g. surface temperatures, populations), we use a commonly-cited figure and
// the scoring tolerance is generous enough that small disagreements do not
// punish a good guess.

export interface SpectrumEntry {
  id: string;
  prompt: string;
  trueValue: number;
  min: number;
  max: number;
  unit: string;
}

export const SPECTRUM_DATA: SpectrumEntry[] = [
  { id: "moon-landing", prompt: "What year did humans first land on the Moon?", trueValue: 1969, min: 1940, max: 2000, unit: "" },
  { id: "everest", prompt: "How tall is Mount Everest?", trueValue: 8849, min: 4000, max: 12000, unit: "m" },
  { id: "venus-temp", prompt: "What is the average surface temperature of Venus?", trueValue: 465, min: 0, max: 900, unit: "C" },
  { id: "human-bones", prompt: "How many bones are in the adult human body?", trueValue: 206, min: 100, max: 400, unit: "" },
  { id: "great-wall", prompt: "How long is the Great Wall of China (total, all branches)?", trueValue: 21196, min: 5000, max: 40000, unit: "km" },
  { id: "speed-light", prompt: "What is the speed of light, in thousands of km per second?", trueValue: 300, min: 100, max: 500, unit: "k km/s" },
  { id: "blue-whale", prompt: "How long can a blue whale grow?", trueValue: 30, min: 10, max: 60, unit: "m" },
  { id: "ww2-end", prompt: "What year did World War II end?", trueValue: 1945, min: 1900, max: 1980, unit: "" },
  { id: "earth-age", prompt: "How old is Earth, in billions of years?", trueValue: 4.5, min: 1, max: 10, unit: "B yrs" },
  { id: "human-heart", prompt: "How many times does the average human heart beat per minute at rest?", trueValue: 72, min: 30, max: 150, unit: "bpm" },
  { id: "marathon", prompt: "How long is a marathon?", trueValue: 42.2, min: 20, max: 60, unit: "km" },
  { id: "boiling", prompt: "At what temperature does water boil at sea level?", trueValue: 100, min: 50, max: 150, unit: "C" },
  { id: "us-states", prompt: "How many states are in the United States?", trueValue: 50, min: 20, max: 80, unit: "" },
  { id: "amazon", prompt: "How long is the Amazon River?", trueValue: 6400, min: 2000, max: 9000, unit: "km" },
  { id: "sun-distance", prompt: "How far is the Sun from Earth, in millions of km?", trueValue: 150, min: 50, max: 300, unit: "M km" },
  { id: "elements", prompt: "How many elements are on the periodic table?", trueValue: 118, min: 50, max: 200, unit: "" },
  { id: "human-teeth", prompt: "How many teeth does a typical adult human have?", trueValue: 32, min: 16, max: 60, unit: "" },
  { id: "olympics-start", prompt: "What year were the first modern Olympic Games held?", trueValue: 1896, min: 1800, max: 1950, unit: "" },
  { id: "pacific-deep", prompt: "How deep is the Mariana Trench (deepest point)?", trueValue: 10935, min: 5000, max: 15000, unit: "m" },
  { id: "cheetah", prompt: "How fast can a cheetah run at top speed?", trueValue: 112, min: 50, max: 150, unit: "km/h" },
  { id: "human-genes", prompt: "Roughly how many protein-coding genes are in the human genome (thousands)?", trueValue: 20, min: 5, max: 100, unit: "k" },
  { id: "saturn-moons", prompt: "How many confirmed moons does Saturn have (approx)?", trueValue: 146, min: 10, max: 300, unit: "" },
  { id: "declaration", prompt: "What year was the U.S. Declaration of Independence signed?", trueValue: 1776, min: 1600, max: 1900, unit: "" },
  { id: "eiffel-height", prompt: "How tall is the Eiffel Tower?", trueValue: 330, min: 100, max: 600, unit: "m" },
  { id: "sahara-area", prompt: "How large is the Sahara Desert, in millions of square km?", trueValue: 9.2, min: 1, max: 20, unit: "M sq km" },
  { id: "human-body-water", prompt: "What percentage of the adult human body is water?", trueValue: 60, min: 20, max: 95, unit: "%" },
  { id: "everest-first", prompt: "What year was Mount Everest first summited?", trueValue: 1953, min: 1900, max: 1990, unit: "" },
  { id: "earth-circumference", prompt: "What is Earth's circumference at the equator?", trueValue: 40075, min: 20000, max: 60000, unit: "km" },
  { id: "sound-speed", prompt: "What is the speed of sound in air, in m per second?", trueValue: 343, min: 100, max: 600, unit: "m/s" },
  { id: "human-lifespan", prompt: "What is the current global average human life expectancy?", trueValue: 73, min: 40, max: 100, unit: "yrs" },
  { id: "berlin-wall", prompt: "What year did the Berlin Wall fall?", trueValue: 1989, min: 1940, max: 2010, unit: "" },
  { id: "moon-distance", prompt: "How far is the Moon from Earth, in thousands of km?", trueValue: 384, min: 100, max: 700, unit: "k km" },
  { id: "blue-whale-weight", prompt: "How much can a blue whale weigh?", trueValue: 150, min: 50, max: 300, unit: "tonnes" },
  { id: "internet-year", prompt: "What year did the World Wide Web become publicly available?", trueValue: 1991, min: 1960, max: 2010, unit: "" },
  { id: "human-cells", prompt: "Roughly how many cells are in the human body (trillions)?", trueValue: 37, min: 1, max: 100, unit: "T" },
  { id: "nile-length", prompt: "How long is the Nile River?", trueValue: 6650, min: 2000, max: 9000, unit: "km" },
  { id: "sun-temp", prompt: "What is the surface temperature of the Sun?", trueValue: 5500, min: 1000, max: 10000, unit: "C" },
  { id: "great-pyramid", prompt: "How tall was the Great Pyramid of Giza originally?", trueValue: 146, min: 50, max: 300, unit: "m" },
  { id: "languages", prompt: "Roughly how many living languages are spoken worldwide?", trueValue: 7000, min: 1000, max: 15000, unit: "" },
  { id: "titanic", prompt: "What year did the Titanic sink?", trueValue: 1912, min: 1850, max: 1970, unit: "" },
  { id: "human-brain-weight", prompt: "How much does the adult human brain weigh?", trueValue: 1400, min: 500, max: 3000, unit: "g" },
  { id: "world-pop", prompt: "What is the world population, in billions?", trueValue: 8, min: 1, max: 15, unit: "B" },
  { id: "antarctica-ice", prompt: "What percent of Antarctica is covered by ice?", trueValue: 98, min: 50, max: 100, unit: "%" },
  { id: "lightning-temp", prompt: "How hot can a lightning bolt get, in thousands of C?", trueValue: 30, min: 5, max: 60, unit: "k C" },
  { id: "first-flight", prompt: "What year did the Wright brothers make their first powered flight?", trueValue: 1903, min: 1850, max: 1950, unit: "" },
  { id: "blood-vessels", prompt: "Total length of blood vessels in the human body, in thousands of km?", trueValue: 100, min: 10, max: 200, unit: "k km" },
  { id: "jupiter-moons", prompt: "How many confirmed moons does Jupiter have (approx)?", trueValue: 95, min: 10, max: 200, unit: "" },
  { id: "redwood", prompt: "How tall can the tallest redwood trees grow?", trueValue: 115, min: 30, max: 200, unit: "m" },
  { id: "honey-jar", prompt: "How many flowers must bees visit to make one jar of honey (millions)?", trueValue: 2, min: 0.5, max: 10, unit: "M" },
  { id: "human-skin", prompt: "What is the total surface area of adult human skin?", trueValue: 2, min: 0.5, max: 5, unit: "sq m" },
  { id: "light-minutes-sun", prompt: "How many minutes does sunlight take to reach Earth?", trueValue: 8.3, min: 1, max: 30, unit: "min" },
  { id: "mercury-year", prompt: "How many Earth days does Mercury take to orbit the Sun?", trueValue: 88, min: 20, max: 300, unit: "days" },
  { id: "human-chromosomes", prompt: "How many chromosomes are in a typical human cell?", trueValue: 46, min: 10, max: 100, unit: "" },
  { id: "gutenberg-bible", prompt: "What year did Gutenberg print his famous Bible?", trueValue: 1455, min: 1300, max: 1600, unit: "" },
  { id: "colosseum-capacity", prompt: "Roughly how many spectators could the Roman Colosseum hold?", trueValue: 50000, min: 10000, max: 100000, unit: "" },
  { id: "octopus-hearts", prompt: "How many hearts does an octopus have?", trueValue: 3, min: 1, max: 10, unit: "" },
  { id: "burj-khalifa", prompt: "How tall is the Burj Khalifa, the world's tallest building?", trueValue: 828, min: 300, max: 1500, unit: "m" },
  { id: "roman-empire-fall", prompt: "What year did the Western Roman Empire fall?", trueValue: 476, min: 100, max: 900, unit: "" },
  { id: "dna-bases", prompt: "How many base pairs are in the human genome, in billions?", trueValue: 3.2, min: 0.5, max: 10, unit: "B" },
  { id: "atlantic-ocean-area", prompt: "How large is the Atlantic Ocean, in millions of square km?", trueValue: 106, min: 30, max: 200, unit: "M sq km" },
  { id: "printing-press-china", prompt: "How many years old is the Great Sphinx of Giza, approximately?", trueValue: 4500, min: 1000, max: 8000, unit: "yrs" },
  { id: "hummingbird-wingbeats", prompt: "How many times per second can a hummingbird beat its wings?", trueValue: 50, min: 10, max: 120, unit: "/s" },
  { id: "pi-digits-known", prompt: "How many digits are there before the decimal point of the value of pi times 100?", trueValue: 3, min: 1, max: 6, unit: "" },
  { id: "french-revolution", prompt: "What year did the French Revolution begin?", trueValue: 1789, min: 1600, max: 1900, unit: "" },
  { id: "atom-diameter", prompt: "What is the diameter of a typical atom, in tenths of a nanometer?", trueValue: 1, min: 0.1, max: 10, unit: "0.1 nm" },
  { id: "sequoia-age", prompt: "How old can the oldest giant sequoia trees grow to be?", trueValue: 3200, min: 500, max: 6000, unit: "yrs" },
  { id: "great-barrier-reef", prompt: "How long is the Great Barrier Reef?", trueValue: 2300, min: 500, max: 5000, unit: "km" },
  { id: "moon-diameter", prompt: "What is the diameter of the Moon?", trueValue: 3475, min: 1000, max: 8000, unit: "km" },
  { id: "black-death-year", prompt: "What year did the Black Death first reach Europe?", trueValue: 1347, min: 1100, max: 1500, unit: "" },
  { id: "human-blood-liters", prompt: "How many liters of blood are in the average adult human body?", trueValue: 5, min: 1, max: 12, unit: "L" },
  { id: "jupiter-diameter", prompt: "What is the diameter of Jupiter, in thousands of km?", trueValue: 140, min: 50, max: 300, unit: "k km" },
  { id: "printing-hiroshima", prompt: "What year was the printing press invented by Gutenberg (movable type in Europe)?", trueValue: 1440, min: 1200, max: 1600, unit: "" },
  { id: "dead-sea-depth", prompt: "How far below sea level is the shore of the Dead Sea?", trueValue: 430, min: 100, max: 900, unit: "m below" },
  { id: "snail-speed", prompt: "How many meters can a garden snail travel in one hour?", trueValue: 45, min: 5, max: 150, unit: "m/h" },
  { id: "sputnik-year", prompt: "What year was Sputnik, the first artificial satellite, launched?", trueValue: 1957, min: 1920, max: 1990, unit: "" },
  { id: "human-dna-length", prompt: "If unwound, how long is the DNA in a single human cell, in meters?", trueValue: 2, min: 0.5, max: 10, unit: "m" },
  { id: "vatican-area", prompt: "How large is Vatican City, the world's smallest country, in hectares?", trueValue: 44, min: 10, max: 200, unit: "ha" },
  { id: "penguin-dive", prompt: "How deep can an emperor penguin dive?", trueValue: 500, min: 100, max: 1000, unit: "m" },
  { id: "magna-carta", prompt: "What year was the Magna Carta sealed?", trueValue: 1215, min: 900, max: 1500, unit: "" },
  { id: "spx-1", prompt: "How long is a day (one full rotation) on Mars, in hours?", trueValue: 24.6, min: 10, max: 48, unit: "hrs" },
  { id: "spx-2", prompt: "How far is Neptune from the Sun, in billions of km?", trueValue: 4.5, min: 1, max: 10, unit: "B km" },
  { id: "spx-3", prompt: "What is Earth's diameter at the equator, in thousands of km?", trueValue: 12.7, min: 5, max: 25, unit: "k km" },
  { id: "spx-4", prompt: "What is the diameter of Mars, in thousands of km?", trueValue: 6.8, min: 2, max: 15, unit: "k km" },
  { id: "spx-5", prompt: "What is the diameter of the Sun, in millions of km?", trueValue: 1.39, min: 0.5, max: 3, unit: "M km" },
  { id: "spx-6", prompt: "What is absolute zero in degrees Celsius?", trueValue: -273, min: -400, max: 0, unit: "C" },
  { id: "spx-7", prompt: "What is the temperature at the core of the Sun, in millions of degrees Celsius?", trueValue: 15, min: 1, max: 40, unit: "M C" },
  { id: "spx-8", prompt: "At what altitude does the International Space Station orbit Earth?", trueValue: 408, min: 100, max: 900, unit: "km" },
  { id: "spx-9", prompt: "How fast does the International Space Station travel in orbit, in km per hour?", trueValue: 28000, min: 10000, max: 50000, unit: "km/h" },
  { id: "spx-10", prompt: "What is Earth's escape velocity, in km per second?", trueValue: 11.2, min: 2, max: 30, unit: "km/s" },
  { id: "spx-11", prompt: "What is the diameter of the Milky Way galaxy, in thousands of light-years?", trueValue: 100, min: 10, max: 300, unit: "k ly" },
  { id: "spx-12", prompt: "How far is Proxima Centauri, the nearest star to the Sun, in light-years?", trueValue: 4.2, min: 1, max: 15, unit: "ly" },
  { id: "spx-13", prompt: "How far away is the Andromeda Galaxy, in millions of light-years?", trueValue: 2.5, min: 0.5, max: 10, unit: "M ly" },
  { id: "spx-14", prompt: "What is the average surface temperature of Mars?", trueValue: -63, min: -150, max: 50, unit: "C" },
  { id: "spx-15", prompt: "How many Earth years does Jupiter take to orbit the Sun?", trueValue: 11.9, min: 2, max: 40, unit: "yrs" },
  { id: "spx-16", prompt: "How many Earth years does Saturn take to orbit the Sun?", trueValue: 29.5, min: 5, max: 80, unit: "yrs" },
  { id: "spx-17", prompt: "How many Earth days does one full rotation of Venus take?", trueValue: 243, min: 50, max: 500, unit: "days" },
  { id: "spx-18", prompt: "The Moon's surface gravity is what percentage of Earth's?", trueValue: 17, min: 5, max: 50, unit: "%" },
  { id: "spx-19", prompt: "A proton is roughly how many times heavier than an electron?", trueValue: 1836, min: 500, max: 5000, unit: "x" },
  { id: "spx-20", prompt: "How far is Voyager 1 from Earth, in billions of km (as of the 2020s)?", trueValue: 24, min: 5, max: 60, unit: "B km" },
  { id: "spx-21", prompt: "What is normal human body temperature in degrees Celsius?", trueValue: 37, min: 30, max: 45, unit: "C" },
  { id: "spx-22", prompt: "At what temperature does nitrogen boil (become gas), in degrees Celsius?", trueValue: -196, min: -273, max: -50, unit: "C" },
  { id: "spx-23", prompt: "At what temperature does gold melt, in degrees Celsius?", trueValue: 1064, min: 300, max: 2500, unit: "C" },
  { id: "spx-24", prompt: "How fast does Earth travel around the Sun, in km per second?", trueValue: 30, min: 5, max: 80, unit: "km/s" },
  { id: "spx-25", prompt: "At what altitude does the Hubble Space Telescope orbit Earth?", trueValue: 540, min: 100, max: 1200, unit: "km" },
  { id: "spx-26", prompt: "How far is Pluto from the Sun on average, in billions of km?", trueValue: 5.9, min: 1, max: 12, unit: "B km" },
  { id: "spx-27", prompt: "What is the diameter of Saturn, in thousands of km?", trueValue: 120, min: 40, max: 250, unit: "k km" },
  { id: "spx-28", prompt: "How far is Mars from the Sun on average, in millions of km?", trueValue: 228, min: 80, max: 500, unit: "M km" },
  { id: "spx-29", prompt: "What is the speed of sound in water, in m per second?", trueValue: 1480, min: 500, max: 3000, unit: "m/s" },
  { id: "spx-30", prompt: "How far is Saturn from the Sun on average, in billions of km?", trueValue: 1.4, min: 0.5, max: 4, unit: "B km" },
  { id: "spx-31", prompt: "How tall is Olympus Mons on Mars, the tallest volcano in the solar system?", trueValue: 22, min: 5, max: 40, unit: "km" },
  { id: "spx-32", prompt: "What percentage of the solar system's total mass is contained in the Sun?", trueValue: 99.8, min: 90, max: 100, unit: "%" },
  { id: "spx-33", prompt: "How many Earth years does Neptune take to orbit the Sun?", trueValue: 165, min: 30, max: 400, unit: "yrs" },
  { id: "spx-34", prompt: "At what temperature does helium boil (become gas), in degrees Celsius?", trueValue: -269, min: -273, max: -100, unit: "C" },
  { id: "spx-35", prompt: "What is the wavelength of red visible light, in nanometers?", trueValue: 700, min: 200, max: 1200, unit: "nm" },
  { id: "spx-36", prompt: "How many days does the Moon take to orbit Earth?", trueValue: 27.3, min: 10, max: 60, unit: "days" },
  { id: "spx-37", prompt: "How large is the Pacific Ocean, in millions of square km?", trueValue: 165, min: 50, max: 300, unit: "M sq km" },
  { id: "spx-38", prompt: "How large is Russia, the world's largest country, in millions of square km?", trueValue: 17.1, min: 5, max: 30, unit: "M sq km" },
  { id: "spx-39", prompt: "How large is Canada, in millions of square km?", trueValue: 9.98, min: 2, max: 20, unit: "M sq km" },
  { id: "spx-40", prompt: "How large is Australia, in millions of square km?", trueValue: 7.69, min: 2, max: 15, unit: "M sq km" },
  { id: "spx-41", prompt: "How large is Greenland, the world's largest island, in millions of square km?", trueValue: 2.16, min: 0.5, max: 6, unit: "M sq km" },
  { id: "spx-42", prompt: "What is the population of India, in billions?", trueValue: 1.43, min: 0.5, max: 3, unit: "B" },
  { id: "spx-43", prompt: "What is the population of China, in billions?", trueValue: 1.41, min: 0.5, max: 3, unit: "B" },
  { id: "spx-44", prompt: "What is the population of the United States, in millions?", trueValue: 335, min: 100, max: 600, unit: "M" },
  { id: "spx-45", prompt: "What is the population of the greater Tokyo metropolitan area, in millions?", trueValue: 37, min: 10, max: 60, unit: "M" },
  { id: "spx-46", prompt: "What is the population of New York City proper, in millions?", trueValue: 8.3, min: 2, max: 20, unit: "M" },
  { id: "spx-47", prompt: "What is the population of Greater London, in millions?", trueValue: 8.9, min: 2, max: 20, unit: "M" },
  { id: "spx-48", prompt: "What is the population of Brazil, in millions?", trueValue: 216, min: 50, max: 400, unit: "M" },
  { id: "spx-49", prompt: "What is the population of Nigeria, in millions?", trueValue: 223, min: 50, max: 400, unit: "M" },
  { id: "spx-50", prompt: "What is the population of the entire African continent, in billions?", trueValue: 1.46, min: 0.5, max: 3, unit: "B" },
  { id: "spx-51", prompt: "How tall is Mount Kilimanjaro, the highest mountain in Africa?", trueValue: 5895, min: 3000, max: 9000, unit: "m" },
  { id: "spx-52", prompt: "How tall is Denali (Mount McKinley), the highest peak in North America?", trueValue: 6190, min: 3000, max: 9000, unit: "m" },
  { id: "spx-53", prompt: "How tall is Aconcagua, the highest mountain in South America?", trueValue: 6961, min: 3000, max: 9000, unit: "m" },
  { id: "spx-54", prompt: "How tall is Mont Blanc, the highest peak in the Alps?", trueValue: 4808, min: 2000, max: 8000, unit: "m" },
  { id: "spx-55", prompt: "How tall is K2, the world's second-highest mountain?", trueValue: 8611, min: 4000, max: 12000, unit: "m" },
  { id: "spx-56", prompt: "How tall is Angel Falls, the world's tallest waterfall?", trueValue: 979, min: 200, max: 2000, unit: "m" },
  { id: "spx-57", prompt: "How tall is the Empire State Building to its tip?", trueValue: 443, min: 200, max: 800, unit: "m" },
  { id: "spx-58", prompt: "How tall is the Elizabeth Tower (Big Ben) in London?", trueValue: 96, min: 30, max: 250, unit: "m" },
  { id: "spx-59", prompt: "How tall is the CN Tower in Toronto?", trueValue: 553, min: 200, max: 1000, unit: "m" },
  { id: "spx-60", prompt: "How tall is the Leaning Tower of Pisa?", trueValue: 57, min: 20, max: 150, unit: "m" },
  { id: "spx-61", prompt: "How long is the Mississippi River?", trueValue: 3766, min: 1000, max: 7000, unit: "km" },
  { id: "spx-62", prompt: "How long is the Yangtze River, the longest in Asia?", trueValue: 6300, min: 2000, max: 9000, unit: "km" },
  { id: "spx-63", prompt: "How long is the Danube River?", trueValue: 2850, min: 1000, max: 6000, unit: "km" },
  { id: "spx-64", prompt: "How long is the Panama Canal?", trueValue: 82, min: 20, max: 200, unit: "km" },
  { id: "spx-65", prompt: "How long is the Suez Canal?", trueValue: 193, min: 50, max: 400, unit: "km" },
  { id: "spx-66", prompt: "How wide is the English Channel at its narrowest point (Strait of Dover)?", trueValue: 33, min: 10, max: 100, unit: "km" },
  { id: "spx-67", prompt: "How long is the general coastline of the United States, in thousands of km?", trueValue: 20, min: 5, max: 50, unit: "k km" },
  { id: "spx-68", prompt: "How long is the Trans-Siberian Railway, the world's longest railway line?", trueValue: 9289, min: 3000, max: 15000, unit: "km" },
  { id: "spx-69", prompt: "How large is Lake Superior, the largest of the Great Lakes, in thousands of square km?", trueValue: 82, min: 20, max: 200, unit: "k sq km" },
  { id: "spx-70", prompt: "How large is the Caspian Sea, the world's largest lake, in thousands of square km?", trueValue: 371, min: 100, max: 800, unit: "k sq km" },
  { id: "spx-71", prompt: "How large is the Amazon Rainforest, in millions of square km?", trueValue: 5.5, min: 1, max: 15, unit: "M sq km" },
  { id: "spx-72", prompt: "How large is Monaco, in hectares?", trueValue: 202, min: 50, max: 800, unit: "ha" },
  { id: "spx-73", prompt: "How large is Central Park in New York City, in hectares?", trueValue: 341, min: 50, max: 1000, unit: "ha" },
  { id: "spx-74", prompt: "What year did Columbus first reach the Americas?", trueValue: 1492, min: 1300, max: 1600, unit: "" },
  { id: "spx-75", prompt: "What year did the American Civil War end?", trueValue: 1865, min: 1780, max: 1950, unit: "" },
  { id: "spx-76", prompt: "What year did World War I begin?", trueValue: 1914, min: 1850, max: 1970, unit: "" },
  { id: "spx-77", prompt: "What year did the Great Fire of London occur?", trueValue: 1666, min: 1400, max: 1800, unit: "" },
  { id: "spx-78", prompt: "What year was the U.S. Constitution signed?", trueValue: 1787, min: 1600, max: 1900, unit: "" },
  { id: "spx-79", prompt: "What year did the California Gold Rush begin?", trueValue: 1848, min: 1700, max: 1950, unit: "" },
  { id: "spx-80", prompt: "What year did Alexander Graham Bell make the first telephone call?", trueValue: 1876, min: 1780, max: 1950, unit: "" },
  { id: "spx-81", prompt: "What year did Alexander Fleming discover penicillin?", trueValue: 1928, min: 1850, max: 1970, unit: "" },
  { id: "spx-82", prompt: "What year was the first iPhone released?", trueValue: 2007, min: 1990, max: 2020, unit: "" },
  { id: "spx-83", prompt: "What year was the storming of the Bastille?", trueValue: 1789, min: 1600, max: 1900, unit: "" },
  { id: "spx-84", prompt: "What year did the Cuban Missile Crisis take place?", trueValue: 1962, min: 1900, max: 2000, unit: "" },
  { id: "spx-85", prompt: "What year was the Battle of Hastings?", trueValue: 1066, min: 800, max: 1400, unit: "" },
  { id: "spx-86", prompt: "What year was William Shakespeare born?", trueValue: 1564, min: 1400, max: 1700, unit: "" },
  { id: "spx-87", prompt: "What year did women gain the right to vote in the United States (19th Amendment)?", trueValue: 1920, min: 1850, max: 1980, unit: "" },
  { id: "spx-88", prompt: "What year was Wikipedia launched?", trueValue: 2001, min: 1980, max: 2020, unit: "" },
  { id: "spx-89", prompt: "What year did the Chernobyl nuclear disaster occur?", trueValue: 1986, min: 1940, max: 2010, unit: "" },
  { id: "spx-90", prompt: "How many hours are in one week?", trueValue: 168, min: 50, max: 300, unit: "hrs" },
  { id: "spx-91", prompt: "How many days are in a leap year?", trueValue: 366, min: 200, max: 500, unit: "days" },
  { id: "spx-92", prompt: "How many seconds are in one day?", trueValue: 86400, min: 20000, max: 150000, unit: "s" },
  { id: "spx-93", prompt: "How many minutes are in one full day?", trueValue: 1440, min: 500, max: 3000, unit: "min" },
  { id: "spx-94", prompt: "How many letters are in the English alphabet?", trueValue: 26, min: 10, max: 50, unit: "" },
  { id: "spx-95", prompt: "How many cards are in a standard deck (without jokers)?", trueValue: 52, min: 20, max: 100, unit: "" },
  { id: "spx-96", prompt: "How many keys are on a standard full-size piano?", trueValue: 88, min: 40, max: 150, unit: "" },
  { id: "spx-97", prompt: "How many squares are on a standard chessboard?", trueValue: 64, min: 20, max: 120, unit: "" },
  { id: "spx-98", prompt: "How many players from one team are on the field in soccer at kickoff?", trueValue: 11, min: 5, max: 20, unit: "" },
  { id: "spx-99", prompt: "How many holes are on a standard full golf course?", trueValue: 18, min: 6, max: 40, unit: "" },
  { id: "spx-100", prompt: "How many rings are in the Olympic symbol?", trueValue: 5, min: 1, max: 12, unit: "" },
  { id: "spx-101", prompt: "How many sides does a standard stop sign have?", trueValue: 8, min: 3, max: 15, unit: "" },
  { id: "spx-102", prompt: "How many colors are traditionally listed in a rainbow?", trueValue: 7, min: 3, max: 14, unit: "" },
  { id: "spx-103", prompt: "How many standard time zones does the world have (one per hour)?", trueValue: 24, min: 10, max: 40, unit: "" },
  { id: "spx-104", prompt: "How many Wonders of the Ancient World are there in the classical list?", trueValue: 7, min: 3, max: 15, unit: "" },
  { id: "spx-105", prompt: "How many member states does the United Nations have?", trueValue: 193, min: 100, max: 250, unit: "" },
  { id: "spx-106", prompt: "How many months is an African elephant's pregnancy?", trueValue: 22, min: 5, max: 40, unit: "months" },
  { id: "spx-107", prompt: "How many weeks is a typical full-term human pregnancy?", trueValue: 40, min: 20, max: 60, unit: "weeks" },
  { id: "spx-108", prompt: "How many years of an 80-year life does a person spend sleeping (about a third)?", trueValue: 26, min: 5, max: 50, unit: "yrs" },
];

export function pickSpectrumEntries(n: number): SpectrumEntry[] {
  const shuffled = [...SPECTRUM_DATA].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, Math.min(n, shuffled.length));
}
