import { User, Question, LeaderboardEntry, Badge, DuelSession, Subject } from "@/types";

// ─── Badges ──────────────────────────────────────────────────────────────────

export const ALL_BADGES: Badge[] = [
  {
    id: "b1",
    name: "First Blood",
    description: "Complete your first quiz",
    icon: "🎯",
    rarity: "common",
    earnedAt: "2024-01-10",
  },
  {
    id: "b2",
    name: "On Fire",
    description: "Maintain a 7-day streak",
    icon: "🔥",
    rarity: "rare",
    earnedAt: "2024-01-17",
  },
  {
    id: "b3",
    name: "Math Wizard",
    description: "Score 100% on 5 math quizzes",
    icon: "🧮",
    rarity: "epic",
    earnedAt: "2024-01-22",
  },
  {
    id: "b4",
    name: "Duel King",
    description: "Win 10 duels in a row",
    icon: "⚔️",
    rarity: "legendary",
    earnedAt: "2024-02-01",
  },
  {
    id: "b5",
    name: "Coin Hoarder",
    description: "Accumulate 10,000 coins",
    icon: "💰",
    rarity: "epic",
    earnedAt: "2024-02-05",
  },
  {
    id: "b6",
    name: "Speed Demon",
    description: "Answer 5 questions in under 5 seconds each",
    icon: "⚡",
    rarity: "rare",
    earnedAt: "2024-01-28",
  },
  {
    id: "b7",
    name: "Poly Grind",
    description: "Complete quizzes in 5 different subjects",
    icon: "📚",
    rarity: "rare",
  },
  {
    id: "b8",
    name: "Night Owl",
    description: "Study after midnight 3 times",
    icon: "🦉",
    rarity: "common",
  },
];

// ─── Users ────────────────────────────────────────────────────────────────────

export const MOCK_USERS: User[] = [
  {
    id: "u1",
    username: "zayded_out",
    displayName: "Zayed Al-Rashid",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=zayed&backgroundColor=4A90D9",
    coins: 14250,
    streak: 23,
    maxStreak: 45,
    xp: 8750,
    level: 12,
    badges: ALL_BADGES.slice(0, 6),
    subjectStats: [
      { subject: "Math", questionsAnswered: 120, correctAnswers: 108, coinsEarned: 3240 },
      { subject: "Coding", questionsAnswered: 95, correctAnswers: 80, coinsEarned: 2400 },
      { subject: "Finance", questionsAnswered: 60, correctAnswers: 52, coinsEarned: 1560 },
      { subject: "SAT/ACT", questionsAnswered: 80, correctAnswers: 65, coinsEarned: 1950 },
      { subject: "Science", questionsAnswered: 45, correctAnswers: 35, coinsEarned: 1050 },
    ],
    joinedAt: "2024-01-01",
    rank: 1,
  },
  {
    id: "u2",
    username: "nova_grind",
    displayName: "Nova Chen",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=nova&backgroundColor=6AABF0",
    coins: 12800,
    streak: 18,
    maxStreak: 30,
    xp: 7200,
    level: 10,
    badges: ALL_BADGES.slice(0, 4),
    subjectStats: [
      { subject: "Science", questionsAnswered: 150, correctAnswers: 135, coinsEarned: 4050 },
      { subject: "Math", questionsAnswered: 90, correctAnswers: 78, coinsEarned: 2340 },
      { subject: "Certifications", questionsAnswered: 40, correctAnswers: 32, coinsEarned: 960 },
    ],
    joinedAt: "2024-01-05",
    rank: 2,
  },
  {
    id: "u3",
    username: "crypto_scholar",
    displayName: "Marcus Webb",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=marcus&backgroundColor=FFD700",
    coins: 11500,
    streak: 31,
    maxStreak: 31,
    xp: 6800,
    level: 9,
    badges: ALL_BADGES.slice(1, 5),
    subjectStats: [
      { subject: "Finance", questionsAnswered: 200, correctAnswers: 180, coinsEarned: 5400 },
      { subject: "Math", questionsAnswered: 70, correctAnswers: 55, coinsEarned: 1650 },
    ],
    joinedAt: "2024-01-08",
    rank: 3,
  },
  {
    id: "u4",
    username: "synth_sage",
    displayName: "Aria Park",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=aria&backgroundColor=9B59B6",
    coins: 9750,
    streak: 12,
    maxStreak: 22,
    xp: 5500,
    level: 8,
    badges: ALL_BADGES.slice(0, 3),
    subjectStats: [
      { subject: "Languages", questionsAnswered: 180, correctAnswers: 162, coinsEarned: 4860 },
      { subject: "SAT/ACT", questionsAnswered: 65, correctAnswers: 50, coinsEarned: 1500 },
    ],
    joinedAt: "2024-01-12",
    rank: 4,
  },
  {
    id: "u5",
    username: "byte_boss",
    displayName: "Jordan Rivers",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=jordan&backgroundColor=2ECC71",
    coins: 8900,
    streak: 7,
    maxStreak: 15,
    xp: 4800,
    level: 7,
    badges: ALL_BADGES.slice(0, 2),
    subjectStats: [
      { subject: "Coding", questionsAnswered: 220, correctAnswers: 198, coinsEarned: 5940 },
      { subject: "Math", questionsAnswered: 50, correctAnswers: 38, coinsEarned: 1140 },
    ],
    joinedAt: "2024-01-15",
    rank: 5,
  },
  {
    id: "u6",
    username: "quiz_queen",
    displayName: "Priya Sharma",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=priya&backgroundColor=E91E63",
    coins: 7600,
    streak: 9,
    maxStreak: 19,
    xp: 4200,
    level: 6,
    badges: ALL_BADGES.slice(0, 2),
    subjectStats: [
      { subject: "SAT/ACT", questionsAnswered: 140, correctAnswers: 119, coinsEarned: 3570 },
      { subject: "Languages", questionsAnswered: 80, correctAnswers: 64, coinsEarned: 1920 },
    ],
    joinedAt: "2024-01-20",
    rank: 6,
  },
];

export const CURRENT_USER = MOCK_USERS[0];

// ─── Questions ────────────────────────────────────────────────────────────────

export const QUIZ_QUESTIONS: Record<Subject, Question[]> = {
  Math: [
    {
      id: "m1",
      subject: "Math",
      question: "If f(x) = 3x² - 2x + 1, what is f'(x)?",
      options: ["6x - 2", "3x - 2", "6x + 1", "3x² - 2"],
      correctAnswer: 0,
      difficulty: "medium",
      coinReward: 30,
      explanation: "The derivative of 3x² is 6x, and the derivative of -2x is -2.",
    },
    {
      id: "m2",
      subject: "Math",
      question: "What is the sum of the interior angles of a hexagon?",
      options: ["540°", "720°", "900°", "360°"],
      correctAnswer: 1,
      difficulty: "medium",
      coinReward: 25,
      explanation: "(n-2) × 180° = (6-2) × 180° = 720°",
    },
    {
      id: "m3",
      subject: "Math",
      question: "Solve: 2x + 5 = 17",
      options: ["x = 4", "x = 6", "x = 7", "x = 5"],
      correctAnswer: 1,
      difficulty: "easy",
      coinReward: 15,
    },
    {
      id: "m4",
      subject: "Math",
      question: "What is log₂(64)?",
      options: ["4", "5", "6", "8"],
      correctAnswer: 2,
      difficulty: "medium",
      coinReward: 30,
      explanation: "2⁶ = 64, so log₂(64) = 6",
    },
    {
      id: "m5",
      subject: "Math",
      question: "The probability of rolling two dice and getting a sum of 7?",
      options: ["1/6", "1/8", "5/36", "7/36"],
      correctAnswer: 0,
      difficulty: "medium",
      coinReward: 35,
      explanation: "There are 6 ways to get 7 out of 36 total outcomes = 6/36 = 1/6",
    },
    {
      id: "m6",
      subject: "Math",
      question: "What is the determinant of [[3, 1], [2, 4]]?",
      options: ["10", "12", "14", "8"],
      correctAnswer: 0,
      difficulty: "hard",
      coinReward: 50,
      explanation: "(3×4) - (1×2) = 12 - 2 = 10",
    },
    {
      id: "m7",
      subject: "Math",
      question: "What is the value of i² where i = √(-1)?",
      options: ["1", "-1", "i", "-i"],
      correctAnswer: 1,
      difficulty: "easy",
      coinReward: 20,
    },
    {
      id: "m8",
      subject: "Math",
      question: "Solve: |3x - 6| = 12",
      options: ["x = 6", "x = -2", "x = 6 or x = -2", "x = 2 or x = -6"],
      correctAnswer: 2,
      difficulty: "medium",
      coinReward: 35,
    },
    {
      id: "m9",
      subject: "Math",
      question: "What is the area of a circle with radius 7?",
      options: ["44π", "49π", "14π", "21π"],
      correctAnswer: 1,
      difficulty: "easy",
      coinReward: 15,
    },
    {
      id: "m10",
      subject: "Math",
      question: "What is the limit of (sin x)/x as x→0?",
      options: ["0", "∞", "1", "undefined"],
      correctAnswer: 2,
      difficulty: "hard",
      coinReward: 50,
    },
  ],
  Science: [
    {
      id: "s1",
      subject: "Science",
      question: "What is the powerhouse of the cell?",
      options: ["Nucleus", "Ribosome", "Mitochondria", "Golgi apparatus"],
      correctAnswer: 2,
      difficulty: "easy",
      coinReward: 15,
    },
    {
      id: "s2",
      subject: "Science",
      question: "What is Newton's second law of motion?",
      options: ["F = mv", "F = ma", "F = m/a", "F = v/t"],
      correctAnswer: 1,
      difficulty: "easy",
      coinReward: 20,
      explanation: "Force equals mass times acceleration (F = ma)",
    },
    {
      id: "s3",
      subject: "Science",
      question: "What is the atomic number of Carbon?",
      options: ["4", "6", "8", "12"],
      correctAnswer: 1,
      difficulty: "easy",
      coinReward: 15,
    },
    {
      id: "s4",
      subject: "Science",
      question: "What type of bond shares electrons equally?",
      options: ["Ionic", "Metallic", "Nonpolar covalent", "Polar covalent"],
      correctAnswer: 2,
      difficulty: "medium",
      coinReward: 30,
    },
    {
      id: "s5",
      subject: "Science",
      question: "What wavelength range is visible light?",
      options: ["400-700 nm", "100-400 nm", "700-1000 nm", "1-100 nm"],
      correctAnswer: 0,
      difficulty: "medium",
      coinReward: 30,
    },
    {
      id: "s6",
      subject: "Science",
      question: "What is Avogadro's number?",
      options: ["6.02 × 10²³", "3.14 × 10²³", "6.02 × 10²²", "1.38 × 10²³"],
      correctAnswer: 0,
      difficulty: "easy",
      coinReward: 20,
    },
    {
      id: "s7",
      subject: "Science",
      question: "Which planet has the most moons?",
      options: ["Jupiter", "Saturn", "Uranus", "Neptune"],
      correctAnswer: 1,
      difficulty: "medium",
      coinReward: 25,
      explanation: "Saturn has 146 confirmed moons, surpassing Jupiter.",
    },
    {
      id: "s8",
      subject: "Science",
      question: "What is the pH of pure water at 25°C?",
      options: ["6", "7", "8", "Depends on pressure"],
      correctAnswer: 1,
      difficulty: "easy",
      coinReward: 15,
    },
    {
      id: "s9",
      subject: "Science",
      question: "What does DNA stand for?",
      options: [
        "Deoxyribonucleic Acid",
        "Dinucleic Acid",
        "Deoxyribose Nucleotide Acid",
        "Dinucleotide Acid",
      ],
      correctAnswer: 0,
      difficulty: "easy",
      coinReward: 15,
    },
    {
      id: "s10",
      subject: "Science",
      question: "What is the speed of light in a vacuum?",
      options: ["3 × 10⁸ m/s", "3 × 10⁶ m/s", "3 × 10¹⁰ m/s", "9 × 10⁸ m/s"],
      correctAnswer: 0,
      difficulty: "easy",
      coinReward: 20,
    },
  ],
  Languages: [
    {
      id: "l1",
      subject: "Languages",
      question: "What is the Spanish word for 'butterfly'?",
      options: ["Mariposa", "Flor", "Pájaro", "Estrella"],
      correctAnswer: 0,
      difficulty: "easy",
      coinReward: 15,
    },
    {
      id: "l2",
      subject: "Languages",
      question: "Which language has the most native speakers worldwide?",
      options: ["English", "Spanish", "Mandarin Chinese", "Hindi"],
      correctAnswer: 2,
      difficulty: "easy",
      coinReward: 15,
    },
    {
      id: "l3",
      subject: "Languages",
      question: "What is the French phrase for 'I love you'?",
      options: ["Je t'aime", "Je vous aime", "Je t'adore", "Both A and B"],
      correctAnswer: 3,
      difficulty: "medium",
      coinReward: 25,
    },
    {
      id: "l4",
      subject: "Languages",
      question: "What writing system does Japanese use?",
      options: ["Only Kanji", "Only Hiragana", "Hiragana, Katakana, and Kanji", "Only Katakana"],
      correctAnswer: 2,
      difficulty: "medium",
      coinReward: 30,
    },
    {
      id: "l5",
      subject: "Languages",
      question: "Which language family does Arabic belong to?",
      options: ["Indo-European", "Semitic", "Sino-Tibetan", "Turkic"],
      correctAnswer: 1,
      difficulty: "medium",
      coinReward: 30,
    },
    {
      id: "l6",
      subject: "Languages",
      question: "How many official languages does Switzerland have?",
      options: ["2", "3", "4", "5"],
      correctAnswer: 2,
      difficulty: "medium",
      coinReward: 25,
      explanation: "German, French, Italian, and Romansh",
    },
    {
      id: "l7",
      subject: "Languages",
      question: "What does 'Carpe Diem' mean in Latin?",
      options: ["Seize the day", "Live forever", "Time flies", "Follow your dreams"],
      correctAnswer: 0,
      difficulty: "easy",
      coinReward: 20,
    },
    {
      id: "l8",
      subject: "Languages",
      question: "What is the German word for 'butterfly'?",
      options: ["Schmetterling", "Vogel", "Blume", "Sonne"],
      correctAnswer: 0,
      difficulty: "medium",
      coinReward: 25,
    },
    {
      id: "l9",
      subject: "Languages",
      question: "What is the most widely spoken Romance language?",
      options: ["French", "Italian", "Portuguese", "Spanish"],
      correctAnswer: 3,
      difficulty: "easy",
      coinReward: 20,
    },
    {
      id: "l10",
      subject: "Languages",
      question: "Which language has the most words?",
      options: ["French", "German", "English", "Japanese"],
      correctAnswer: 2,
      difficulty: "medium",
      coinReward: 25,
    },
  ],
  "SAT/ACT": [
    {
      id: "sat1",
      subject: "SAT/ACT",
      question: "If 3x + 7 = 22, what is the value of 6x + 5?",
      options: ["30", "35", "40", "25"],
      correctAnswer: 1,
      difficulty: "medium",
      coinReward: 30,
      explanation: "3x = 15, x = 5. Then 6(5) + 5 = 35",
    },
    {
      id: "sat2",
      subject: "SAT/ACT",
      question: "What is the meaning of 'ephemeral'?",
      options: ["Long-lasting", "Short-lived", "Mysterious", "Abundant"],
      correctAnswer: 1,
      difficulty: "medium",
      coinReward: 25,
    },
    {
      id: "sat3",
      subject: "SAT/ACT",
      question: "A car travels 240 miles in 4 hours. What is its average speed?",
      options: ["50 mph", "55 mph", "60 mph", "65 mph"],
      correctAnswer: 2,
      difficulty: "easy",
      coinReward: 15,
    },
    {
      id: "sat4",
      subject: "SAT/ACT",
      question: "Which sentence contains a dangling modifier?",
      options: [
        "Running down the street, the dog barked loudly.",
        "Running down the street, I saw the dog.",
        "The dog, barking loudly, ran down the street.",
        "I ran down the street, and the dog barked.",
      ],
      correctAnswer: 0,
      difficulty: "hard",
      coinReward: 45,
    },
    {
      id: "sat5",
      subject: "SAT/ACT",
      question: "A rectangle's length is 3 times its width. If perimeter = 48, find the area.",
      options: ["108", "96", "81", "72"],
      correctAnswer: 0,
      difficulty: "hard",
      coinReward: 50,
      explanation: "2(3w + w) = 48 → w = 6, l = 18. Area = 18 × 6 = 108",
    },
    {
      id: "sat6",
      subject: "SAT/ACT",
      question: "What literary device is used: 'The wind whispered through the trees'?",
      options: ["Metaphor", "Simile", "Personification", "Alliteration"],
      correctAnswer: 2,
      difficulty: "easy",
      coinReward: 20,
    },
    {
      id: "sat7",
      subject: "SAT/ACT",
      question: "What is the synonym for 'ubiquitous'?",
      options: ["Rare", "Omnipresent", "Singular", "Obscure"],
      correctAnswer: 1,
      difficulty: "medium",
      coinReward: 30,
    },
    {
      id: "sat8",
      subject: "SAT/ACT",
      question: "If a² + b² = 25 and ab = 12, what is (a + b)²?",
      options: ["37", "49", "61", "25"],
      correctAnswer: 1,
      difficulty: "hard",
      coinReward: 50,
      explanation: "(a+b)² = a² + 2ab + b² = 25 + 24 = 49",
    },
    {
      id: "sat9",
      subject: "SAT/ACT",
      question: "Which word correctly completes: 'The results were _____ than expected'?",
      options: ["more better", "more worse", "worse", "worst"],
      correctAnswer: 2,
      difficulty: "medium",
      coinReward: 20,
    },
    {
      id: "sat10",
      subject: "SAT/ACT",
      question: "What percentage of 80 is 20?",
      options: ["15%", "20%", "25%", "30%"],
      correctAnswer: 2,
      difficulty: "easy",
      coinReward: 15,
    },
  ],
  Coding: [
    {
      id: "c1",
      subject: "Coding",
      question: "What is the time complexity of binary search?",
      options: ["O(n)", "O(n²)", "O(log n)", "O(n log n)"],
      correctAnswer: 2,
      difficulty: "medium",
      coinReward: 35,
    },
    {
      id: "c2",
      subject: "Coding",
      question: "What does CSS stand for?",
      options: [
        "Computer Style Sheet",
        "Cascading Style Sheet",
        "Creative Style System",
        "Coded Style Sheet",
      ],
      correctAnswer: 1,
      difficulty: "easy",
      coinReward: 15,
    },
    {
      id: "c3",
      subject: "Coding",
      question: "Which data structure uses LIFO (Last In, First Out)?",
      options: ["Queue", "Stack", "Linked List", "Tree"],
      correctAnswer: 1,
      difficulty: "easy",
      coinReward: 20,
    },
    {
      id: "c4",
      subject: "Coding",
      question: "What is a closure in JavaScript?",
      options: [
        "A function that terminates a program",
        "A function that has access to its outer scope variables",
        "A function that is immediately invoked",
        "A function without parameters",
      ],
      correctAnswer: 1,
      difficulty: "medium",
      coinReward: 35,
    },
    {
      id: "c5",
      subject: "Coding",
      question: "What is the output of: console.log(typeof null)?",
      options: ["null", "undefined", "object", "string"],
      correctAnswer: 2,
      difficulty: "medium",
      coinReward: 30,
      explanation: "This is a known JavaScript quirk — typeof null returns 'object'.",
    },
    {
      id: "c6",
      subject: "Coding",
      question: "Which sorting algorithm has O(n log n) average time complexity?",
      options: ["Bubble Sort", "Insertion Sort", "Quick Sort", "Selection Sort"],
      correctAnswer: 2,
      difficulty: "medium",
      coinReward: 35,
    },
    {
      id: "c7",
      subject: "Coding",
      question: "What does API stand for?",
      options: [
        "Automated Programming Interface",
        "Application Programming Interface",
        "Advanced Protocol Integration",
        "Application Protocol Interface",
      ],
      correctAnswer: 1,
      difficulty: "easy",
      coinReward: 15,
    },
    {
      id: "c8",
      subject: "Coding",
      question: "What is the result of 5 === '5' in JavaScript?",
      options: ["true", "false", "TypeError", "undefined"],
      correctAnswer: 1,
      difficulty: "easy",
      coinReward: 20,
      explanation: "=== checks type and value. 5 is number, '5' is string — not equal.",
    },
    {
      id: "c9",
      subject: "Coding",
      question: "Which HTTP method is used to update a resource?",
      options: ["GET", "POST", "PUT", "DELETE"],
      correctAnswer: 2,
      difficulty: "easy",
      coinReward: 20,
    },
    {
      id: "c10",
      subject: "Coding",
      question: "In Python, what is a list comprehension?",
      options: [
        "A way to import lists from libraries",
        "A concise way to create lists using a single expression",
        "A method to compare two lists",
        "A built-in function to flatten nested lists",
      ],
      correctAnswer: 1,
      difficulty: "medium",
      coinReward: 30,
    },
  ],
  Finance: [
    {
      id: "f1",
      subject: "Finance",
      question: "What does ROI stand for?",
      options: [
        "Rate of Income",
        "Return on Investment",
        "Revenue over Investment",
        "Risk of Inflation",
      ],
      correctAnswer: 1,
      difficulty: "easy",
      coinReward: 15,
    },
    {
      id: "f2",
      subject: "Finance",
      question: "What is compound interest?",
      options: [
        "Interest calculated only on the principal",
        "Interest calculated on both principal and accumulated interest",
        "A fixed monthly fee charged by banks",
        "Interest that decreases over time",
      ],
      correctAnswer: 1,
      difficulty: "easy",
      coinReward: 20,
    },
    {
      id: "f3",
      subject: "Finance",
      question: "What is a bull market?",
      options: [
        "A market with falling prices",
        "A market with rising prices",
        "A market with stable prices",
        "A market in a recession",
      ],
      correctAnswer: 1,
      difficulty: "easy",
      coinReward: 15,
    },
    {
      id: "f4",
      subject: "Finance",
      question: "What is the P/E ratio?",
      options: [
        "Profit to Earnings ratio",
        "Price to Earnings ratio",
        "Profit to Equity ratio",
        "Principal to Expense ratio",
      ],
      correctAnswer: 1,
      difficulty: "medium",
      coinReward: 30,
    },
    {
      id: "f5",
      subject: "Finance",
      question: "What is diversification in investing?",
      options: [
        "Putting all money in one stock",
        "Spreading investments across different assets",
        "Only investing in bonds",
        "Converting all assets to cash",
      ],
      correctAnswer: 1,
      difficulty: "easy",
      coinReward: 20,
    },
    {
      id: "f6",
      subject: "Finance",
      question: "If you invest $1000 at 10% annual compound interest, how much after 3 years?",
      options: ["$1,300", "$1,310", "$1,331", "$1,350"],
      correctAnswer: 2,
      difficulty: "medium",
      coinReward: 35,
      explanation: "1000 × (1.10)³ = 1000 × 1.331 = $1,331",
    },
    {
      id: "f7",
      subject: "Finance",
      question: "What is a mutual fund?",
      options: [
        "A type of savings account",
        "A pooled investment vehicle managed by professionals",
        "A government bond",
        "A loan from multiple banks",
      ],
      correctAnswer: 1,
      difficulty: "medium",
      coinReward: 25,
    },
    {
      id: "f8",
      subject: "Finance",
      question: "What does 'liquidity' refer to in finance?",
      options: [
        "The amount of debt a company has",
        "How easily an asset can be converted to cash",
        "The interest rate on loans",
        "The total value of a company",
      ],
      correctAnswer: 1,
      difficulty: "medium",
      coinReward: 30,
    },
    {
      id: "f9",
      subject: "Finance",
      question: "What is inflation?",
      options: [
        "Decrease in general price levels",
        "Increase in general price levels over time",
        "A rise in stock market prices",
        "Decrease in unemployment",
      ],
      correctAnswer: 1,
      difficulty: "easy",
      coinReward: 15,
    },
    {
      id: "f10",
      subject: "Finance",
      question: "What is the rule of 72?",
      options: [
        "A tax regulation for retirement accounts",
        "A rule to estimate years to double your investment at a given rate",
        "A formula for calculating loan payments",
        "A guideline for stock market investing",
      ],
      correctAnswer: 1,
      difficulty: "medium",
      coinReward: 35,
      explanation: "Divide 72 by the annual interest rate to estimate years to double money.",
    },
  ],
  Certifications: [
    {
      id: "cert1",
      subject: "Certifications",
      question: "What does AWS stand for?",
      options: [
        "Advanced Web Services",
        "Amazon Web Services",
        "Automated Web Systems",
        "Applied Web Solutions",
      ],
      correctAnswer: 1,
      difficulty: "easy",
      coinReward: 15,
    },
    {
      id: "cert2",
      subject: "Certifications",
      question: "What does the CIA triad stand for in cybersecurity?",
      options: [
        "Control, Integrity, Access",
        "Confidentiality, Integrity, Availability",
        "Cyber, Information, Access",
        "Confidentiality, Information, Authorization",
      ],
      correctAnswer: 1,
      difficulty: "medium",
      coinReward: 30,
    },
    {
      id: "cert3",
      subject: "Certifications",
      question: "What is the OSI model?",
      options: [
        "Open System Interconnection model — a 7-layer network framework",
        "Operating System Interface model",
        "Online Security Integration model",
        "Open Source Infrastructure model",
      ],
      correctAnswer: 0,
      difficulty: "medium",
      coinReward: 35,
    },
    {
      id: "cert4",
      subject: "Certifications",
      question: "Which CompTIA certification focuses on cybersecurity?",
      options: ["CompTIA A+", "CompTIA Network+", "CompTIA Security+", "CompTIA Cloud+"],
      correctAnswer: 2,
      difficulty: "easy",
      coinReward: 20,
    },
    {
      id: "cert5",
      subject: "Certifications",
      question: "What does HTTPS stand for?",
      options: [
        "Hyper Text Transfer Protocol Secure",
        "High Transfer Text Protocol System",
        "Hyper Transfer Text Protocol Security",
        "High Text Transfer Protocol Secure",
      ],
      correctAnswer: 0,
      difficulty: "easy",
      coinReward: 15,
    },
    {
      id: "cert6",
      subject: "Certifications",
      question: "What is a VPN?",
      options: [
        "Virtual Private Network",
        "Very Protected Node",
        "Virtual Public Network",
        "Verified Private Network",
      ],
      correctAnswer: 0,
      difficulty: "easy",
      coinReward: 15,
    },
    {
      id: "cert7",
      subject: "Certifications",
      question: "What type of attack involves overwhelming a server with traffic?",
      options: ["Phishing", "SQL Injection", "DDoS", "Man-in-the-Middle"],
      correctAnswer: 2,
      difficulty: "medium",
      coinReward: 30,
    },
    {
      id: "cert8",
      subject: "Certifications",
      question: "What does SQL stand for?",
      options: [
        "Structured Query Language",
        "System Query Language",
        "Sequential Query Logic",
        "Structured Queue Logic",
      ],
      correctAnswer: 0,
      difficulty: "easy",
      coinReward: 15,
    },
    {
      id: "cert9",
      subject: "Certifications",
      question: "What is the purpose of a firewall?",
      options: [
        "Speed up internet connection",
        "Monitor and control incoming/outgoing network traffic",
        "Encrypt all data transmissions",
        "Manage user accounts",
      ],
      correctAnswer: 1,
      difficulty: "easy",
      coinReward: 20,
    },
    {
      id: "cert10",
      subject: "Certifications",
      question: "What does DNS stand for?",
      options: [
        "Dynamic Network System",
        "Domain Name System",
        "Direct Network Service",
        "Data Node Server",
      ],
      correctAnswer: 1,
      difficulty: "easy",
      coinReward: 15,
    },
  ],
};

// ─── Leaderboard ──────────────────────────────────────────────────────────────

export const LEADERBOARD_ENTRIES: LeaderboardEntry[] = [
  {
    rank: 1,
    user: MOCK_USERS[0],
    coinsThisWeek: 2450,
    streak: 23,
    change: "same",
  },
  {
    rank: 2,
    user: MOCK_USERS[1],
    coinsThisWeek: 2100,
    streak: 18,
    change: "up",
    changeAmount: 1,
  },
  {
    rank: 3,
    user: MOCK_USERS[2],
    coinsThisWeek: 1870,
    streak: 31,
    change: "down",
    changeAmount: 1,
  },
  {
    rank: 4,
    user: MOCK_USERS[3],
    coinsThisWeek: 1640,
    streak: 12,
    change: "up",
    changeAmount: 2,
  },
  {
    rank: 5,
    user: MOCK_USERS[4],
    coinsThisWeek: 1520,
    streak: 7,
    change: "down",
    changeAmount: 1,
  },
  {
    rank: 6,
    user: MOCK_USERS[5],
    coinsThisWeek: 1310,
    streak: 9,
    change: "up",
    changeAmount: 1,
  },
];

// ─── Duel Session ─────────────────────────────────────────────────────────────

export const MOCK_DUEL: DuelSession = {
  id: "duel1",
  challenger: MOCK_USERS[0],
  opponent: MOCK_USERS[1],
  challengerScore: 0,
  opponentScore: 0,
  currentQuestion: 0,
  questions: QUIZ_QUESTIONS["Math"],
  status: "active",
};

// ─── Utility ──────────────────────────────────────────────────────────────────

export const XP_PER_LEVEL = 1000;

export function getLevelProgress(xp: number): { level: number; progress: number; xpToNext: number } {
  const level = Math.floor(xp / XP_PER_LEVEL) + 1;
  const progress = ((xp % XP_PER_LEVEL) / XP_PER_LEVEL) * 100;
  const xpToNext = XP_PER_LEVEL - (xp % XP_PER_LEVEL);
  return { level, progress, xpToNext };
}

export function formatCoins(coins: number): string {
  if (coins >= 1000) return `${(coins / 1000).toFixed(1)}K`;
  return coins.toString();
}

export const SUBJECT_ICONS: Record<Subject, string> = {
  Math: "🧮",
  Science: "🔬",
  Languages: "🌍",
  "SAT/ACT": "📝",
  Coding: "💻",
  Finance: "💰",
  Certifications: "🏆",
};

export const SUBJECT_COLORS: Record<Subject, string> = {
  Math: "#4A90D9",
  Science: "#2ECC71",
  Languages: "#9B59B6",
  "SAT/ACT": "#E67E22",
  Coding: "#1ABC9C",
  Finance: "#FFD700",
  Certifications: "#E91E63",
};
